#!/usr/bin/env python3
"""One-shot builder for _newsletter_oi_data.py — run once then delete if desired."""
from pathlib import Path


def row(name, ep, guest, quote, cat, belief, op, arch, h, pres, fail, con, sig, emo, adapt, ai):
    return (name, ep, guest, quote, cat, belief, op, arch, h, pres, fail, con, sig, emo, adapt, ai)


EP = {
    "second_brain": ("How to build your PM second brain with ChatGPT", "Amir Klein"),
    "claude_code": ("Everyone should be using Claude Code more", "Lenny Rachitsky"),
    "essential": ("Essential reading for product builders—part 1", "Lenny Rachitsky"),
    "vibe_coding": ("What people are vibe coding (and actually using)", "Lenny Rachitsky"),
    "glossary": ("An AI glossary", "Lenny Rachitsky"),
    "job_market": ("State of the product job market in 2025", "Lenny Rachitsky"),
    "evals": ("Beyond vibe checks: A PM's complete guide to evals", "Aman Khan"),
    "prototyping": ("A guide to AI prototyping for product managers", "Colin Matthews"),
    "unfair_pm": ("Product manager is an unfair role. So work unfairly.", "Tal Raviv"),
    "duolingo": ("How Duolingo reignited user growth", "Jorge Mazal"),
}

DATA = []

# --- Amir Klein (6) ---
ep, g = EP["second_brain"]
DATA += [
    row("Context Externalization Tax", ep, g,
        "Your brain is for thinking, not storage—offload context into a structured second brain so judgment compounds instead of resetting every Monday.",
        "productivity", "Cognitive load is the hidden tax on PM quality; external systems beat heroic memory.",
        "Capture decisions, stakeholders, and open threads in a living GPT project; treat reload-from-zero as a failure mode not a ritual.",
        "Solo PM or small squad with one canonical context repository everyone (including AI) reads before acting.",
        "That teammates share your mental model without the artifact; that ChatGPT remembers what you forgot to paste.",
        "New PM onboarding mid-quarter; exec asks for instant status; you return from vacation.",
        "AI confidently hallucinates status because context was never written down; you become the bottleneck again.",
        "Preaches augmentation while many still treat AI as a one-off prompt toy without persistent memory.",
        "Slack DMs substitute for documentation; leaders praise being on top of things while rewarding firefighting.",
        "Shame when caught not knowing details; resistance from ICs who see docs as bureaucracy.",
        "Weekly context refresh ritual; template prompts that force stakeholder map and decision log updates.",
        "Second brains become mandatory PM infrastructure—hiring screens for whether you maintain a system of record."),
    row("Judgment Amplification Not Replacement", ep, g,
        "The second brain should multiply your taste and tradeoffs, not automate decisions you have not earned the context to make.",
        "ai_product", "AI scales output only where human judgment already exists as ground truth.",
        "Use GPT to stress-test PRDs, surface contradictions, and draft options—but keep approval on ambiguous tradeoffs.",
        "PM who owns narrative quality with AI as sparring partner, not autonomous PM bot.",
        "That more drafts equals better decisions; that the model shares your political read of the room.",
        "Leadership wants overnight strategy memo; eng wants spec detail; design wants rationale.",
        "Rubber-stamping AI strategy that ignores power dynamics; analysis paralysis from infinite drafts.",
        "Newsletter sells second brain while warning that judgment cannot be outsourced.",
        "PMs paste AI output into Slack without editing; leaders spot generic voice instantly.",
        "Imposter syndrome when AI sounds smarter; fear of being found out for using help.",
        "Explicit human-owns tags on decisions; red-team prompts for stakeholder objections.",
        "PM job splits into context curator plus judgment owner; agents handle drafts, humans own bets."),
    row("Reload Cost Spiral", ep, g,
        "Every time you re-explain the product to an AI or a new teammate, you pay a reload tax that compounds across meetings and tools.",
        "operations", "Institutional memory must be cheaper to load than to reconstruct.",
        "Version a single source-of-truth doc; link it in every GPT session; ban starting prompts from blank state.",
        "Org where onboarding is read the brain not shadow me for a month.",
        "That verbal handoffs scale; that people will read the doc without enforcement.",
        "Reorgs; PM transitions; vendor and tool switches.",
        "Tribal knowledge walks out the door; AI gives plausible wrong answers from stale fragments.",
        "Advocates AI speed while arguing unstructured speed creates rework.",
        "Repeated let me catch you up meetings; same questions in every staff sync.",
        "Fatigue from being the human API; resentment when docs drift out of date.",
        "Doc owner rotation; stale-after-14-days nudges; GPT project pinned in team wiki.",
        "Reload cost becomes measurable KPI—time-to-context for humans and agents alike."),
    row("Confidence Gap Paradox", ep, g,
        "AI makes you faster at producing artifacts while sometimes lowering confidence that you understand the problem deeply.",
        "psychology", "Speed without comprehension creates brittle conviction.",
        "Alternate AI-assisted sprints with forced articulation: explain the decision without looking at the draft.",
        "PM team that celebrates I changed my mind after synthesis, not volume of docs shipped.",
        "That confidence and velocity move together; that stakeholders cannot smell shallow fluency.",
        "Demo day pressure; board prep; cross-functional alignment sessions.",
        "Overconfident roadmap based on polished AI prose; hidden gaps surface at launch.",
        "Tool increases output while author warns output can mask shallow thinking.",
        "PM cannot answer follow-up without reopening chat; nods along using AI vocabulary.",
        "Anxiety about being exposed; performative expertise in written channels.",
        "Pre-mortem prompts; require what would change my mind on every major doc.",
        "Eval culture extends to PM judgment—confidence must be calibrated like model scores."),
    row("Prototype Bridge Doctrine", ep, g,
        "The second brain should feed prototypes—not replace them—because stakeholders believe what they click, not what they read.",
        "product_development", "Artifacts earn alignment when they reduce imagination tax.",
        "Chain context doc to AI-assisted spec to quick prototype to feedback to update brain.",
        "PM who ships clickable truth before debate spirals in abstract nouns.",
        "That a perfect doc removes need to show; that prototypes can be skipped for internal bets.",
        "Skeptical eng; design wants pixels; sales wants demo.",
        "Endless PRD iteration in chat; no shared reference object; misaligned mental models persist.",
        "Text-heavy second brain advice in a world moving to vibe-coded demos.",
        "Weeks of narrative docs; no Figma or code until late; surprise at eng estimates.",
        "Tension between writers and builders; politics of who owns the prototype.",
        "Bolt or Lovable handoff from brain exports; label prototype as question not answer.",
        "Second brains link directly to prototype repos—context and click-through become one system."),
    row("Personality-First Setup", ep, g,
        "Configure the second brain with your voice, values, and decision heuristics first—generic GPT setup produces generic PM work.",
        "tooling", "Personalization is not vanity; it is how AI respects your organizational reality.",
        "Spend first sessions teaching constraints, tone, anti-patterns, and how we win here before task prompts.",
        "PM with bespoke GPT project instructions reviewed quarterly with manager.",
        "That default ChatGPT is good enough; that personality config is one-and-done.",
        "New role; company pivot; brand or regulatory constraints shift.",
        "Homogenized roadmaps that sound like every other AI PM; loss of trust from execs who know your voice.",
        "Calls for systemization while emphasizing deeply personal setup.",
        "Copy-paste prompts from Twitter; output reads like newsletter not your company.",
        "Fear of not doing it right; perfectionism delaying setup.",
        "Shared starter template with required voice and constraints section; peer review of system prompts.",
        "Personal agent profiles become portable assets—candidates bring their configured brain."),
]

# --- Claude Code (8) ---
ep, g = EP["claude_code"]
DATA += [
    row("Claude Local Reframe", ep, g,
        "Treat Claude Code as a local operator on your machine—not a chatbot in a tab—so file system, git, and terminal become the product surface.",
        "tooling", "The IDE is the new browser for knowledge work when agents can act on files.",
        "Run agent in repo root; grant scoped permissions; iterate in branch not in Google Doc.",
        "Engineer-PM hybrid working directly in codebase with agent as pair.",
        "That cloud chat is sufficient; that security teams will allow unrestricted file access.",
        "Enterprise security review; air-gapped environments; monorepo complexity.",
        "Shadow IT agents on laptops; leaked secrets in prompts; broken builds from unreviewed agent commits.",
        "Newsletter democratizes coding agents while enterprises lag on policy.",
        "PMs still request eng for trivial text changes; engineers gatekeep repo access.",
        "Fear of breaking prod; turf war between IT and builders.",
        "Sandbox branches; pre-commit hooks; documented permission tiers for non-eng.",
        "Local agents become default GTM for every SaaS—if it cannot run in your repo, it is legacy."),
    row("Source-Directory GTM", ep, g,
        "Your repository is the go-to-market surface—README, examples, and MCP configs sell the product better than landing pages alone.",
        "gtm", "Developers buy what they can clone and run in thirty seconds.",
        "Ship eval fixtures, sample apps, and integration folders as first-class product; measure clone-to-activation.",
        "Dev-tool company where docs live beside code and releases are tagged in git.",
        "That marketing site traffic matters more than GitHub stars for PLG.",
        "Competitor fork; open-source alternative; enterprise wants on-prem.",
        "Stale examples; broken quickstart; brilliant product with empty examples folder.",
        "Preaches repo-as-GTM in newsletter economy still obsessed with webinars.",
        "Sales promises features not in repo; eng maintains examples as afterthought.",
        "Tension between devrel and product on who owns samples.",
        "CI fails if examples break; treat sample drift as P0 bug.",
        "AI agents read your repo to sell for you—bad structure equals invisible product."),
    row("MCP Hub Architecture", ep, g,
        "MCP turns Claude into a hub that composes tools—plan for many small servers, not one mega-integration.",
        "architecture", "Interoperability beats monolithic plugins when models and tools churn quarterly.",
        "Expose each capability as isolated MCP server with tight schemas.",
        "Platform team curating internal MCP catalog with security review per connector.",
        "That one vendor MCP will cover all workflows; that schemas never break clients.",
        "Tool explosion; model switch breaks half the connectors.",
        "MCP sprawl without discovery; secrets scattered across ten local servers.",
        "Standardization hype vs every team shipping bespoke MCP.",
        "Duplicate MCPs for Jira; no owner for deprecation.",
        "Platform vs line-of-business fight over who approves connectors.",
        "Internal MCP registry with ownership tags; version pinning documented.",
        "MCP becomes org chart for agents—governance is the product job."),
    row("Assumption Ledger Discipline", ep, g,
        "Maintain a living ledger of assumptions agents and humans are acting on—update when reality diverges.",
        "decision_systems", "Hidden assumptions are how AI and teams ship wrong things confidently.",
        "After each agent session, log what we assumed and assign human to validate top three risks.",
        "PM and eng pair reviewing assumption ledger in weekly sync.",
        "That assumptions are obvious; that the model will flag its own blind spots.",
        "Pivot; model upgrade; customer segment shift.",
        "Ledger rots; becomes performative; decisions proceed on vibes anyway.",
        "Calls for rigor in agent era while celebrating move-fast shipping.",
        "Surprise postmortems: we assumed X since January.",
        "Blame on model when assumption was human and unwritten.",
        "Template ASSUMPTIONS.md in repo; agent prompted to append not overwrite.",
        "Assumption ledgers merge with eval datasets—wrong beliefs become test cases."),
    row("Said-vs-Did COO Pattern", ep, g,
        "Use agents to compare what leadership said in meetings and docs versus what shipped in git—close the loop like a COO with perfect memory.",
        "governance", "Organizations drift when narrative and execution are not continuously reconciled.",
        "Ingest transcripts plus commits; weekly diff report of promises vs merges.",
        "Chief-of-staff function partially automated for scale-ups.",
        "That leaders intend follow-through when they forget; that public shaming is the goal.",
        "All-hands commitments; OKR season; reorg rhetoric.",
        "Weaponized reports; culture of surveillance; false positives from ambiguous language.",
        "Empowers IC truth-telling while risking political backlash.",
        "Leaders stop speaking precisely; Slack goes oral-only.",
        "Trust collapse between exec and product org.",
        "Private team-level reports first; human adjudication before escalation.",
        "Every company gets an AI COO—winners use it for learning not punishment."),
    row("Reverse-Build Documentation", ep, g,
        "Generate docs from the codebase after the fact instead of writing specs that instantly lie—truth flows from what runs.",
        "documentation", "Living code is the only honest spec in agentic development.",
        "Ship feature, then agent writes user-facing and internal docs from diff, then human edits for intent.",
        "Team where technical writers pair with agents on release branches.",
        "That upfront PRDs stay accurate; that agents capture why not only what.",
        "Regulated industries needing advance approval.",
        "Docs describe deprecated paths; missing rationale for tradeoffs.",
        "Advocates reverse docs while schools still teach PRD-first waterfall.",
        "Docs lag releases by quarters; support answers from stale help center.",
        "Writers fear obsolescence; PMs fear loss of narrative control.",
        "Doc PRs required before merge to main; link doc commit to feature flag.",
        "Documentation becomes continuous export from repo—static wikis die."),
    row("Terminal Aversion Tax", ep, g,
        "The largest adoption blocker for Claude Code is terminal phobia—products must meet people in GUI or they forfeit half the org.",
        "adoption", "Interface shape determines who gets to be a builder.",
        "Offer GUI wrappers, VS Code extensions, and guided flows before demanding shell fluency.",
        "Company with parallel tracks: terminal-native power users and GUI-first PMs.",
        "That everyone will learn bash if the tool is good enough; that CLI is the only real path.",
        "Designers and PMs asked to just use the terminal; IT blocks shells.",
        "Two-class organization: builders vs beggars; shadow no-code tools proliferate.",
        "Celebrates terminal power while acknowledging most people will never live there.",
        "PMs ask eng for one-line changes; expensive pairing sessions.",
        "Shame in workshops; seniors gatekeep real workflow.",
        "Invest in desktop apps and IDE plugins; terminal optional not mandatory.",
        "Agent UIs replace terminals for 80%—CLI remains power-user minority."),
    row("Self-Driving Docs Loop", ep, g,
        "Docs that update themselves when code changes—treat documentation as a CI job, not a quarterly project.",
        "automation", "If docs are not coupled to release mechanics, they are fiction.",
        "Hook agent on merge to main: summarize diff, update affected pages, open PR for human skim.",
        "Platform eng owning doc-bot with PM review on customer-facing pages.",
        "That teams will manually update; that auto-docs are good enough without edit.",
        "Major refactor; rename explosion; API breaking changes.",
        "Nonsense auto-generated pages; SEO spam internal wiki.",
        "Automation promise vs need for human voice on sensitive topics.",
        "Support tickets cite wrong docs; customers trust less.",
        "Tech writers vs eng on blame for wrong doc.",
        "Human-in-the-loop approval for external docs; auto-only for internal.",
        "Docs become test artifacts—if doc PR fails CI, release blocks."),
]

# --- Essential reading (8) ---
ep, g = EP["essential"]
DATA += [
    row("Monkey Ownership Trap", ep, g,
        "When everyone can build, the monkey of execution jumps to the PM by default—ownership without authority becomes the quiet tax of the builder era.",
        "org_design", "Democratized building does not democratize accountability.",
        "Name explicit DRI before prototype exists; refuse to be default integrator for every AI experiment.",
        "Flat builder org where PM is accidental router of all side quests.",
        "That no DRI means collaborative; that speed excuses unclear ownership.",
        "Hackathon week; exec asks for ten AI demos; eng ships without PM in loop.",
        "PM burnout as human Jira; nothing ships to production because everything is a demo.",
        "Celebrates builder empowerment while warning PM becomes monkey catcher.",
        "Slack flood of look what I built; PM cannot say no without political cost.",
        "Resentment from PMs; pride from builders who hate coordination.",
        "Public DRI tags on every initiative; kill list for orphan prototypes.",
        "Agent swarms need ownership protocols—monkey problem scales with agent count."),
    row("Agency Autonomy Plus Efficacy", ep, g,
        "True agency requires both autonomy to act and efficacy—the belief your action will move the system—not just permission slides.",
        "psychology", "Empowerment theater fails when people learn their effort does not change outcomes.",
        "Pair delegated authority with visible feedback loops; measure whether actions changed metrics or policies.",
        "Learning org investing in efficacy through small wins, not slogans.",
        "That autonomy alone fixes morale; that senior titles imply efficacy.",
        "Layoffs; reorg; strategy whiplash.",
        "Learned helplessness; cynical compliance; quiet quitting with OKR theater.",
        "Curates empowerment content while market destroys PM efficacy signals.",
        "All-hands says move fast; middle manager vetoes experiments.",
        "Cynicism masked as professionalism.",
        "Publish decision log showing which IC bets shipped; celebrate reversals.",
        "AI gives autonomy to everyone—efficacy gap widens without feedback discipline."),
    row("Taste Gap Widening", ep, g,
        "When execution is cheap, taste—not tooling—becomes the scarce differentiator between slop and products people love.",
        "product_craft", "More builders does not mean more good products.",
        "Invest in reference sets, design critique, and kill criteria before scaling AI output.",
        "Small senior circle with veto on customer-facing quality.",
        "That volume of experiments discovers taste automatically.",
        "Competitor ships AI feature parity; board wants AI everywhere.",
        "Feature zoo; brand dilution; users churn from inconsistent quality.",
        "Essential reading list elevates taste while ecosystem rewards shipping slop.",
        "Metrics up on engagement hacks; NPS flat; design complaints dismissed.",
        "Design vs growth fight; PM caught optimizing clicks.",
        "Taste rubric in PR review; fewer bigger bets with editorial bar.",
        "Taste becomes hiring moat—tasteless orgs drown in AI-generated sameness."),
    row("Pretend Learning Loop", ep, g,
        "Consuming AI content without building is pretend learning—it feels like progress while skill atrophy continues.",
        "learning", "Information diet is not capability building.",
        "Cap newsletter and podcast time with equal build hours; ship weekly micro-artifact.",
        "PM who tracks build-to-consume ratio in public.",
        "That awareness equals adoption; that courses substitute for reps.",
        "Performance review asks for AI fluency; no time blocked to build.",
        "Imposter syndrome hidden behind curated reading lists; no portfolio of work.",
        "Newsletter itself is consumption—meta tension with build-more advice.",
        "Bookmarks hundreds of posts; repo empty; asks eng to prototype.",
        "FOMO anxiety; shame about not being technical enough.",
        "Build buddy accountability; share failures not just highlights.",
        "Learning splits: consumers vs builders—latter compound advantage."),
    row("Three Attributes Bar", ep, g,
        "The builders who win combine curiosity, agency, and communication—missing one collapses the triangle under AI load.",
        "talent", "Skills are necessary but attributes determine whether skills compound.",
        "Hire and coach for all three; do not promote brilliant curmudgeons or articulate passengers.",
        "High-trust team with explicit feedback on communication gaps.",
        "That coding skill alone suffices; that communication is soft optional.",
        "Remote async; cross-functional AI projects; exec visibility scarce.",
        "Brilliant builder nobody follows; great communicator no delivery.",
        "Timeless attributes advice in era obsessed with tool tips.",
        "Silent high performers overlooked; loud mediocre promoted.",
        "Identity tied to being the smart one vs being effective.",
        "360 on communication; pairing curious juniors with agency mentors.",
        "AI rewards communicators who can steer agents—curiosity without communication wastes tokens."),
    row("Market Pull Over Push", ep, g,
        "Build where market pull already exists—AI makes push cheap, so push without pull becomes noise squared.",
        "strategy", "Distribution of attention is scarcer than distribution of code.",
        "Validate pull signals before building; use AI to amplify pull, not invent demand.",
        "Founder-PM watching organic usage clusters before roadmap commit.",
        "That if we ship they will come; that AI demos create demand.",
        "Investor pressure for AI roadmap; internal pet projects.",
        "Spray of AI features nobody asked for; burn on sales-led push.",
        "Builder empowerment narrative vs discipline of pull-first.",
        "Usage flat while demo views spike; sales asks for custom AI.",
        "FOMO vs focus pain for leaders.",
        "Hold AI ideas until three independent pull signals; kill push-only bets.",
        "Pull detection becomes core PM analytics—agents generate, humans select for pull."),
    row("Barbell Input Diet", ep, g,
        "Consume both timeless principles and bleeding-edge tactics—middle-of-the-road product content ages instantly in AI waves.",
        "learning", "Career insurance is barbelled: classics plus frontier reps.",
        "Schedule deep reads on fundamentals plus weekly hands-on with newest tools; ignore mushy middle.",
        "Operator with canon books plus daily agent experiments.",
        "That one newsletter subscription is enough; that fundamentals are boring.",
        "Tool churn weekly; strategy principles stable for decades.",
        "Chasing tactics without judgment; preaching principles without shipping.",
        "Curated reading list is itself middle—reader must add extremes.",
        "Only reads summaries; no primary sources; no reps.",
        "Intellectual snobbery vs hustle culture split.",
        "Personal canon doc plus changelog of tools tried.",
        "Barbell widens—timeless judgment even more valuable as tactics obsolesce weekly."),
    row("Chef Versus Cook", ep, g,
        "AI makes everyone a cook who can follow recipes—chefs who invent recipes and taste outcomes own the category.",
        "product_craft", "Recipe following scales; recipe invention is the moat.",
        "Force why prompts: why this architecture, why this metric, why now—before accepting AI recipe.",
        "Team with chefs on platform and cooks on execution with clear ladder between.",
        "That prompting templates equal product management.",
        "Commodity features; race to same Copilot checklist.",
        "Identical AI products; price war; no retention story.",
        "Teaches reading list while tools turn PMs into cooks by default.",
        "Team ships competitor clone in a week; no differentiation.",
        "Senior chefs bored; junior cooks overconfident.",
        "Chef time protected from ticket load; cooks mentored toward invention.",
        "Organizations split chef strategists from cook operators—middle hollows faster."),
]

# --- Vibe coding survey (7) ---
ep, g = EP["vibe_coding"]
DATA += [
    row("N-of-1 Software Norm", ep, g,
        "The dominant vibe-coded product is software for one person—the builder—flipping the venture scale assumption.",
        "market", "Personal utility is a valid product category when build cost approaches zero.",
        "Ship for yourself first; expand only when others pull; resist premature SaaS packaging.",
        "Solo builder with portfolio of micro-tools not one startup.",
        "That every tool must become a company; that n-of-1 cannot teach GTM.",
        "Investor asks for TAM; friends want your script.",
        "Abandoned side projects; no maintenance; security holes in personal tools.",
        "Survey celebrates indie builders while ecosystem funds only scale plays.",
        "Twitter demos; zero users besides author.",
        "Loneliness of builder; imposter vs founder identity.",
        "Open-source personal tools; let community fork if pull appears.",
        "Software long tail explodes—billions of n-of-1 apps, few winners take all."),
    row("Chrome Extension Gravity Well", ep, g,
        "Vibe coders cluster on browser extensions because distribution is one click and scope is bounded—gravity well hides harder problems.",
        "distribution", "Extension store is the path of least resistance for first ship.",
        "Use extensions to validate workflow pain; plan escape velocity to platform if traction.",
        "Indie hackers shipping five extensions before one real business.",
        "That extension success transfers to mobile or enterprise automatically.",
        "Manifest V3 policy changes; store takedowns; API breakage.",
        "Portfolio of 200-user extensions; no moat; support burden.",
        "Highlights extensions while AI enables full apps—gravity may be temporary.",
        "Builders avoid backend because scary; everything is DOM hacks.",
        "Store review anxiety; fear of Google policy.",
        "Treat extension as MVP wedge; document migration path early.",
        "Extensions become agent attach points—new distribution for AI workflows."),
    row("Plain English Remote Engineer", ep, g,
        "Non-engineers now describe software in plain English and remote-control an AI engineer—the role boundary is negotiation not job title.",
        "role_evolution", "Intent expression separates builders from typists.",
        "Write acceptance criteria in English; let agent implement; review diff like a tech lead.",
        "PM with production access via agent and design partner for taste.",
        "That no code means no responsibility for production incidents.",
        "Incident in prod from PM merge; security audit failure.",
        "Blameless postmortem reveals PM shipped without review; eng revokes access.",
        "Celebrates PM builders while companies still deny repo access.",
        "PMs secretly vibe code; eng discovers in outage.",
        "Territorial eng; PM empowerment shame.",
        "Shared review norms; agent audit logs; blameless but accountable.",
        "Plain-English engineering becomes literal job requirement for PMs."),
    row("Self-Use Filter", ep, g,
        "The strongest filter for vibe-coded products is daily self-use—if you do not use it, it is a demo not a product.",
        "validation", "Dogfooding is the only honest eval when build is free.",
        "Mandate seven-day self-use before sharing; kill if you reach for the old tool.",
        "Builder who deletes more projects than they publish.",
        "That launch day usage predicts retention; that friends' praise counts.",
        "Social media pressure to announce; hackathon deadlines.",
        "Ghost tools; broken auth you never hit; embarrassed silence after launch.",
        "Survey of what people use vs what they tweet—contradiction by design.",
        "Product Hunt spike; author never opens app again.",
        "Ego attachment to announced projects.",
        "Public build log with use metrics; shame OK for killed tools.",
        "Self-use telemetry becomes default analytics for solo builders."),
    row("Tool Consolidation Fatigue", ep, g,
        "Vibe coders report consolidating stacks because tool sprawl has higher cognitive cost than feature gaps.",
        "tooling", "Fewer tools with deeper fluency beats infinite beta signups.",
        "Pick one IDE, one agent, one deploy path for a quarter; measure throughput not novelty.",
        "Small team standardizing on Cursor plus one backend.",
        "That best-of-breed always wins; that FOMO misses nothing important.",
        "New model drop weekly; influencer stack posts daily.",
        "Migration whiplash; lost context; no muscle memory.",
        "Newsletter ecosystem profits from tool churn while advising consolidation.",
        "Calendar full of trying new apps; roadmap empty.",
        "Anxiety of being left behind.",
        "Tool budget: one experiment slot per month; document why switched.",
        "Consolidation winners capture agents—second-tool markets shrink."),
    row("Accidental Distribution", ep, g,
        "Many vibe-coded products find users accidentally—support forum post, reply guy, internal slack share—not deliberate GTM.",
        "distribution", "Build in public works when artifact is genuinely useful, not when marketing is performative.",
        "Optimize for shareable moment of value; leave breadcrumbs in communities where pain is vocal.",
        "Indie builder whose growth is 90% word of mouth from one use case.",
        "That growth can be planned like enterprise funnel; that SEO is dead.",
        "Platform algorithm change; community ban; copycat overnight.",
        "One-hit wonder; cannot reproduce; burns out answering DMs.",
        "Accidental distribution praised while VCs demand repeatable GTM.",
        "Viral tweet; no onboarding; churn 100%.",
        "Uncomfortable with sales identity.",
        "Capture origin story in onboarding; double down on accidental use case.",
        "AI search and social amplify accidental hits—plan for spike or die."),
    row("Women Building Visibility Gap", ep, g,
        "Survey highlights women building in public at rising rates—visibility does not equal funding or enterprise adoption yet.",
        "inclusion", "Democratized tools lower build barrier; institutions lag on capital and trust.",
        "Amplify builders' work with credit; design communities that reduce harassment tax of public building.",
        "Diverse indie builders network sharing stacks and safety practices.",
        "That build access alone fixes representation in outcomes.",
        "Harassment in replies; dismissive investors; caregiving time constraints.",
        "Talented builders go private; lose network effects of public learning.",
        "Celebrates progress while data still shows funding gaps.",
        "Women builders over-mentored, under-capitalized.",
        "Exhaustion from being symbol and builder at once.",
        "Paid communities; sponsorship; intentional spotlight without tokenism.",
        "Lower build barrier shifts fight to distribution and capital—new bottlenecks."),
]

# --- AI glossary (8) ---
ep, g = EP["glossary"]
DATA += [
    row("Stacked Adaptation Ladder", ep, g,
        "Models are pretrained, then fine-tuned, then RLHF'd, then tool-connected—each layer adds capability and new failure modes.",
        "technical_literacy", "No single knob controls behavior; stack literacy prevents magical thinking.",
        "Map your product bet to which layer actually needs to change before retraining fantasies.",
        "ML platform team educating PMs on what fine-tune vs prompt vs RAG solves.",
        "That bigger base model makes fine-tune unnecessary; that RLHF fixes all safety.",
        "Vendor promises one-click custom model; compliance asks for explainability.",
        "Wrong layer investment; months lost fine-tuning when prompt plus eval would suffice.",
        "Glossary simplifies stack while vendors obscure for sales.",
        "PMs say we need fine-tune without data; eng sighs.",
        "Fear of looking dumb in ML meetings.",
        "Decision tree poster in wiki; escalate to platform when layer unclear.",
        "PMs must know ladder—budget and timeline conversations depend on it."),
    row("Hallucination as Missing Context", ep, g,
        "Hallucination is often missing context presented as fluent completion—the fix is retrieval and scope, not shame.",
        "quality", "Confident wrong answers are a context engineering problem.",
        "Narrow task scope; ground with RAG; refuse to answer outside corpus; measure groundedness.",
        "Support bot with strict corpus and escalation path.",
        "That users can prompt-engineer away bad retrieval; that bigger model ends hallucinations.",
        "Legal asks for guarantees; sales demos unconstrained.",
        "Trust collapse after one high-profile wrong answer.",
        "Defines hallucination clinically while market uses it as moral panic word.",
        "PM disables feature after one bug; eng wants eval investment.",
        "Fear of shipping customer-facing AI.",
        "Grounded eval suite; show citations in UI; human handoff triggers.",
        "Hallucination management becomes standard PM skill like latency budgets."),
    row("Agent Spectrum Discipline", ep, g,
        "Agents sit on a spectrum from suggest to act to orchestrate—confusion on placement causes every AI disaster story.",
        "product_development", "Agency level is a product decision with liability attached.",
        "Label every feature with spectrum position; upgrade only with eval evidence and rollback.",
        "PM plus legal plus eng signing agency changelog.",
        "That users want full autonomy because demos look cool.",
        "Competitor launches autonomous refund bot.",
        "Over-automation scandal; under-automation irrelevance.",
        "Glossary clarifies spectrum while marketing demands autonomous wording.",
        "Slide says agent; product is autocomplete.",
        "Legal vs product vs eng triangle fights.",
        "Public agency meter in release notes; customer setting to reduce autonomy.",
        "Companies publish agent tiers like security SLAs—market matures."),
    row("Complexity Trap", ep, g,
        "Teams over-build eval frameworks with dozens of judges—complexity becomes excuse to avoid human labeling.",
        "anti_pattern", "Simple high-signal evals beat ornate low-signal dashboards.",
        "Cap judges at handful; prefer human spot checks for new failure modes.",
        "Lean eval team resisting enterprise QA theater.",
        "That more metrics equals more control.",
        "Consultant sells eval platform; integration takes quarter.",
        "Dashboard green; users furious; maintenance hell.",
        "Sophisticated guide risks readers over-engineering.",
        "Engineers build eval platform not evals.",
        "Pride in internal tooling over user outcomes.",
        "Start with ten tests in pytest; grow only on proven pain.",
        "Eval tooling consolidates—complexity losers abandon bespoke stacks."),
    row("Sparse Human Signal", ep, g,
        "Production gives sparse thumbs and silence—most valuable eval signal is intentionally collected, not passively hoped for.",
        "metrics", "Implicit feedback is insufficient for rare catastrophic failures.",
        "Instrument explicit feedback on high-risk paths; sample sessions; interview on failures.",
        "Growth plus PM plus trust-safety sharing labeled incident set.",
        "That analytics dashboards replace evals; that silence means satisfaction.",
        "Rare wrong medical or legal advice; no thumbs down.",
        "Catastrophic tail event; no prior test.",
        "Calls for human signal while products minimize friction to give feedback.",
        "Low NPS response rate ignored.",
        "Legal blocks asking users about errors.",
        "Targeted outreach after high-stakes sessions; bounty for failure reports.",
        "Synthetic users plus real incidents hybridize sparse signal problem."),
    row("Step-Level Mapping", ep, g,
        "Agent failures need step-level eval mapping—which tool call failed—not only final answer grading.",
        "agents", "End-state scores hide recoverable mid-chain bugs.",
        "Log trajectories; assert per-step constraints; replay with mocks.",
        "Agent platform team providing trace UI for PM review.",
        "That final response quality is enough.",
        "Multi-step booking agent; payment succeeded but wrong date.",
        "Green eval on output; user harm on process.",
        "Holistic eval advice must include step granularity.",
        "PMs evaluate chat transcript prose only.",
        "Eng hoards trace tools.",
        "PM trained on trace reading; step evals in shared repo.",
        "Step-level eval standard for any agent touching money or PII."),
    row("RLHF Gaming Surface", ep, g,
        "RLHF teaches models to please raters—which can diverge from truth, safety, or your product values.",
        "alignment", "Helpful-sounding is not the same as correct or on-brand.",
        "Test for sycophancy and refusals; add product-specific evals beyond vendor defaults.",
        "Trust and safety reviewing model upgrades for new failure modes.",
        "That base model alignment equals your alignment.",
        "Launch in regulated domain; model refuses valid tasks or lies politely.",
        "Brand damage from overly agreeable assistant; user manipulation via flattery.",
        "Explains RLHF limits while vendors imply safety solved.",
        "Users report creepy agreeableness; PM blames prompt.",
        "Ethics vs growth on personality tuning.",
        "Custom rubric judges; A/B on tone with retention and truth metrics.",
        "Every product needs RLHF-on-RLHF—layered alignment for brand."),
    row("Vibe Coding Definition Tension", ep, g,
        "Vibe coding means building by feel with AI—but the term now spans hobbyists, pros, and marketing slop.",
        "culture", "Shared language matters because hiring, policy, and quality bars depend on it.",
        "Define vibe coding level in your org: exploratory, prototype, or production; different gates for each.",
        "Company with vibe coding sandbox separate from production SDLC.",
        "That everyone means the same thing when they say vibe code.",
        "Exec mandates vibe code everything; security panic.",
        "Production incidents from hobby workflow; talent mismatch in hiring.",
        "Glossary defines term while headline culture dilutes it.",
        "Job posts say vibe code; interview expects leetcode.",
        "Identity fights between real engineers and new builders.",
        "Written policy on what vibe coding can touch; prod requires review.",
        "Term splits—professional agentic engineering vs casual vibe coding."),
]

# --- Job market 2025 (7) ---
ep, g = EP["job_market"]
DATA += [
    row("PM Recovery Asymmetry", ep, g,
        "PM hiring recovers unevenly—senior strategy and AI-native builders rebound faster than mid-level coordinators.",
        "career", "The barbell in PM employment is structural, not cyclical.",
        "Position as builder-strategist; document shipped artifacts; avoid resume-only coordination narrative.",
        "Job seeker with public portfolio of AI prototypes plus metrics stories.",
        "That 2023 layoffs were temporary blip; that old PM playbook returns.",
        "Hundreds apply per role; AI screens resumes.",
        "Years of coordination experience discounted; age bias masked as skills gap.",
        "Reports recovery while mid-level still struggles—both true.",
        "Coordinators cannot show code or demos; seniors overcrowd openings.",
        "Shame about title without company; desperation applying.",
        "Reskill publicly; target companies with AI product surface.",
        "PM market splits permanently—coordination PM role shrinks."),
    row("AI PM Explosion", ep, g,
        "AI PM titles multiply faster than shared definition—hiring managers conflate prompt ownership, ML literacy, and classic PM.",
        "hiring", "Title inflation hides whether role is strategy, evals, or demo theater.",
        "Ask which layer: data, evals, UX, GTM, or platform; match your proof points.",
        "Candidate clarifying AI PM scope in interviews with written questions.",
        "That AI PM means one thing; that courses equal qualification.",
        "Recruiter keyword match; take-home ambiguous.",
        "Hired for prompts, fired for no strategy; or hired for strategy, drowned in labeling.",
        "Market creates AI PM roles faster than curricula.",
        "Job description lists 40 skills; salary generic PM.",
        "Imposter syndrome for non-ML PMs.",
        "Publish your AI PM thesis; narrow search to matching scope.",
        "AI PM splinters into eval PM, agent PM, data PM—specialization accelerates."),
    row("Remote Baseline Reset", ep, g,
        "Remote is baseline for many PM roles again—but elite networks still concentrate advantage in hybrid hubs.",
        "workplace", "Geography matters less for job access, more for career compound interest.",
        "Invest in remote-native visibility: writing, demos, async leadership proof.",
        "Distributed team with intentional in-person summits not daily office mandate.",
        "That remote equals equal opportunity; that async needs no skill.",
        "Company mandates return-to-office for leadership track.",
        "Invisible PM loses promo to office neighbor; timezone penalty.",
        "Celebrates remote openness while Bay Area gravity section admits concentration.",
        "Camera-off culture; weak written updates.",
        "FOMO on hallway decisions.",
        "Document decisions in public channels; fly to key summits quarterly.",
        "Remote PMs need agent-augmented visibility—bots do not replace narrative presence."),
    row("Bay Area Gravity", ep, g,
        "Despite remote hiring, network density in Bay Area still accelerates fundraising, hiring, and acquihire odds.",
        "geography", "Talent markets are global; power markets remain local.",
        "Remote work for job; strategic trips for network; or relocate for category-defining companies.",
        "Founder commuting monthly to SF from Austin.",
        "That LinkedIn DMs replace warm intros; that cost of living math is only financial.",
        "Layoff cluster in one metro; competitor poaching locally.",
        "Isolation from deal flow; slower trust building.",
        "Remote baseline vs gravity—tension not contradiction.",
        "Builders in secondary cities under-indexed on cap table events.",
        "Resentment of coastal centrism.",
        "Paid communities bridging geography; intentional intro programs.",
        "Virtual networks rise but gravity weakens slowly—plan accordingly."),
    row("Layoffs Slowing Not Stopping", ep, g,
        "Layoffs slowed in 2025 but did not stop—survivor guilt and zero-sum internal competition persist.",
        "org_psychology", "Stability headlines do not restore pre-2023 trust.",
        "Build internal optionality; external network warm; avoid single-company identity.",
        "Tenured PM maintaining external advisory and public work.",
        "That job security returned because headlines improved.",
        "Quiet hiring freeze; AI efficiency mandates.",
        "Survivors overloaded; quality drops; best leave voluntarily.",
        "Optimistic market report vs lived employee anxiety.",
        "Managers stop 1:1 career talk; teams hoard work.",
        "Fear of being next; competition not collaboration.",
        "Negotiate scope not just comp; document impact for external market.",
        "Smaller teams permanent—each PM owns broader surface with agents."),
    row("Product Engineer Elevation", ep, g,
        "Product engineer roles rise—hybrids who ship full stack with product judgment absorb work that was PM plus eng handoff.",
        "role_evolution", "Handoff tax is target for elimination.",
        "Decide if you become hybrid or partner tightly with one; mid PM without either path is squeezed.",
        "Team of product engineers with PM on discovery only.",
        "That PM headcount stays stable as eng absorbs; that hybrids have no politics.",
        "Eng culture rejects PM code; PM culture rejects eng titles.",
        "Duplicate work; unclear DRI; slower than either solo hybrid.",
        "Reports product engineer rise while PM recovery also claimed.",
        "Job posts want coding PM; interview no repo access.",
        "Title envy; identity threat.",
        "Pairing model with shared metrics; hybrid track in career ladder.",
        "Product engineer default for new startups—classic PM triad rare early."),
    row("Capex Ambiguity Fog", ep, g,
        "AI capex boom creates hiring ambiguity—companies hire aggressively and freeze simultaneously depending on GPU ROI narrative.",
        "macro", "Spend on intelligence is strategic until Wall Street flinches.",
        "Read employer cash and inference cost story; prefer products with unit economics not only demos.",
        "Candidate evaluating employer GPU dependency and revenue mix.",
        "That AI investment means secure jobs; that hype equals stability.",
        "Quarterly earnings; sudden hiring freeze; project killed after datacenter bill.",
        "Join AI team dissolved; stock compensation underwater.",
        "Bullish AI job market vs capex fear headlines coexist.",
        "Recruiters ghost after offer stage; teams double-staffed then cut.",
        "Whiplash anxiety.",
        "Diversify skills toward revenue-near roles; avoid pure research bet without funding.",
        "PMs near revenue and cost of inference survive cuts—far from model lab."),
]

# --- Aman Khan evals (10) ---
ep, g = EP["evals"]
DATA += [
    row("Evals Over Prompts", ep, g,
        "When quality regresses, teams rewrite prompts—winners rewrite evals because prompts are hypotheses and evals are the experiment.",
        "quality", "Prompt optimization without measurement is superstition.",
        "Freeze prompt; improve eval set; then iterate prompt against stable tests.",
        "PM-owned eval suite reviewed with eng before any prompt change ships.",
        "That clever prompt fixes structural retrieval gap.",
        "Exec demands tone change Friday; model upgrade Monday.",
        "Prompt churn with no learning; same failures recurring.",
        "Newsletter title says beyond vibe checks while industry still prompt-chases.",
        "Ten prompt variants in Slack; zero logged failures.",
        "PM vs eng blame ping-pong.",
        "Eval-first change protocol in team wiki.",
        "Prompt libraries commoditize—eval IP is moat."),
    row("Driving Test Metaphor", ep, g,
        "Shipping AI without evals is like granting drivers licenses without road tests—fluency in chat is not competence in traffic.",
        "governance", "Society will demand proof of performance for consequential AI.",
        "Build driving test scenarios from production near-misses before scaling user count.",
        "Regulated-adjacent product with published eval criteria.",
        "That beta label absolves quality; that users are the test.",
        "PR crisis; regulator inquiry; competitor publicizes your failures.",
        "Injury metaphor becomes legal reality; brand collapse.",
        "Strong metaphor vs startups skipping tests for speed.",
        "We are still learning used in incident postmortem.",
        "Legal wants sign-off; product wants ship.",
        "Publish internal test pass rates; external trust follows.",
        "Driving tests become certification industry for agents."),
    row("Three Modalities Framework", ep, g,
        "Eval inputs split across text, code, and multimodal—each modality needs different harness and failure taxonomy.",
        "quality", "One eval pipeline cannot judge what it cannot perceive.",
        "Split eval suites by modality; shared rubric but separate fixtures.",
        "Platform team providing modality-specific eval templates.",
        "That text judges suffice for vision features.",
        "Image feature shipped with only string asserts.",
        "Silent failures on UI layout; accessibility regressions.",
        "Unified framework preached; reality requires specialization.",
        "PM writes text-only evals for screenshot product.",
        "Modality experts siloed.",
        "Hire or partner for modality depth; do not fake with GPT-only judges.",
        "Multimodal eval tooling market explodes—PM specifies scenarios per sense."),
    row("Four-Part Judge Design", ep, g,
        "A useful LLM judge needs task definition, rubric, exemplars, and aggregation—skipping a part produces theater metrics.",
        "quality", "Judges are products, not one-line prompts.",
        "Document all four parts; version judges like APIs; calibrate against humans.",
        "Eval engineer pairing with PM on rubric workshops.",
        "That higher judge count improves signal.",
        "Board wants AI quality dashboard by quarter end.",
        "Contradictory judges; false green; wasted tokens.",
        "Simplicity advice vs complex judge reality.",
        "Copy-paste judge prompt from blog; scores nonsense.",
        "Dispute whether 4 or 5 is good enough.",
        "Judge design doc required in PR template.",
        "Judge marketplaces emerge—buy calibrated judges per domain."),
    row("Ninety Percent Calibration Bar", ep, g,
        "LLM judges must agree with human experts roughly ninety percent on golden set before they scale—below that you automate noise.",
        "quality", "Un calibrated automation accelerates wrong conclusions.",
        "Label hundred cases with two humans; tune judge until kappa acceptable; only then auto-score.",
        "Human labeling squad for high-stakes eval paths.",
        "That any agreement is fine; that judges replace humans entirely.",
        "Cost pressure to remove labelers; CEO wants fully automated QA.",
        "Automated greenwashing; ship regressions at scale.",
        "Calibration rigor vs move fast narrative.",
        "Celebrate high automated score; humans disagree in spot check.",
        "Labelers undervalued; PMs skip hard labeling.",
        "Budget human calibration; treat as COGS not R&D optional.",
        "Calibration-as-a-service for judges—standard enterprise buy."),
    row("Eval Iteration Loop", ep, g,
        "Eval work is a loop: ship, fail, capture, add to suite, fix—not a one-time checklist before launch.",
        "operations", "Quality compounds through repository of failures.",
        "Every incident becomes eval within 48 hours; weekly eval review in product meeting.",
        "Team with eval backlog prioritized like bug backlog.",
        "That launch evals are sufficient; that failures are shameful not data.",
        "Model vendor update; silent behavior drift.",
        "Same bug class recurs monthly; team tired of firefighting.",
        "Iteration preached; roadmaps skip eval maintenance sprints.",
        "Postmortem without new test case.",
        "Blame users for edge cases.",
        "Eval debt labeled on dashboard; OKR on regression rate.",
        "Continuous eval ops role appears—SRE for probabilistic products."),
    row("Evals as Final Boss", ep, g,
        "Prompting is level one; evals are the final boss—teams that never graduate stay in demo purgatory.",
        "culture", "Maturity is measured by failure archive depth not demo polish.",
        "Gate production on eval pass; celebrate adding hard cases.",
        "Org where PM promo requires shipped eval suite story.",
        "That demo applause equals product-market fit.",
        "Sales sells capability evals prove false.",
        "Churn after flashy launch; eng loses trust in PM.",
        "Gamified metaphor vs boring maintenance work.",
        "Leaders want demo in all-hands; eval work invisible.",
        "Hero culture vs systems culture.",
        "Make eval wins visible in all-hands; tie bonuses to regression metrics.",
        "Final boss mindset separates AI-native companies from wrappers."),
    row("Complexity Trap", ep, g,
        "Teams over-build eval frameworks with dozens of judges—complexity becomes excuse to avoid human labeling.",
        "anti_pattern", "Simple high-signal evals beat ornate low-signal dashboards.",
        "Cap judges at handful; prefer human spot checks for new failure modes.",
        "Lean eval team resisting enterprise QA theater.",
        "That more metrics equals more control.",
        "Consultant sells eval platform; integration takes quarter.",
        "Dashboard green; users furious; maintenance hell.",
        "Sophisticated guide risks readers over-engineering.",
        "Engineers build eval platform not evals.",
        "Pride in internal tooling over user outcomes.",
        "Start with ten tests in pytest; grow only on proven pain.",
        "Eval tooling consolidates—complexity losers abandon bespoke stacks."),
    row("Sparse Human Signal", ep, g,
        "Production gives sparse thumbs and silence—most valuable eval signal is intentionally collected, not passively hoped for.",
        "metrics", "Implicit feedback is insufficient for rare catastrophic failures.",
        "Instrument explicit feedback on high-risk paths; sample sessions; interview on failures.",
        "Growth plus PM plus trust-safety sharing labeled incident set.",
        "That analytics dashboards replace evals; that silence means satisfaction.",
        "Rare wrong medical or legal advice; no thumbs down.",
        "Catastrophic tail event; no prior test.",
        "Calls for human signal while products minimize friction to give feedback.",
        "Low NPS response rate ignored.",
        "Legal blocks asking users about errors.",
        "Targeted outreach after high-stakes sessions; bounty for failure reports.",
        "Synthetic users plus real incidents hybridize sparse signal problem."),
    row("Step-Level Mapping", ep, g,
        "Agent failures need step-level eval mapping—which tool call failed—not only final answer grading.",
        "agents", "End-state scores hide recoverable mid-chain bugs.",
        "Log trajectories; assert per-step constraints; replay with mocks.",
        "Agent platform team providing trace UI for PM review.",
        "That final response quality is enough.",
        "Multi-step booking agent; payment succeeded but wrong date.",
        "Green eval on output; user harm on process.",
        "Holistic eval advice must include step granularity.",
        "PMs evaluate chat transcript prose only.",
        "Eng hoards trace tools.",
        "PM trained on trace reading; step evals in shared repo.",
        "Step-level eval standard for any agent touching money or PII."),
]

# --- Colin Matthews prototyping (8) ---
ep, g = EP["prototyping"]
DATA += [
    row("Three-Tier Tool Ladder", ep, g,
        "PM prototyping tools split into chat ideation, browser builders, and IDE agents—using wrong tier wastes time or creates false confidence.",
        "tooling", "Match tool power to fidelity needed for the decision at hand.",
        "Tier one for problem framing; tier two for clickable; tier three for integration truth.",
        "PM fluent in when to escalate tier with checkpoint.",
        "That one tool should do everything; that tier three is always worth it.",
        "Exec wants production tomorrow; you shipped tier two.",
        "Beautiful mock; integration fails; credibility lost.",
        "Guide teaches tiers while hype says skip to agents.",
        "Team standardizes on one vendor religiously.",
        "Shame about not using hardest tool.",
        "Decision card: which tier for which question.",
        "Tiers blur as tools merge—ladder logic still applies."),
    row("Bolt Browser Limit", ep, g,
        "Browser-native builders like Bolt hit walls on auth, backend, and state—fine for narrative demos, dangerous for technical validation.",
        "constraints", "Frontend-only truth is not product truth.",
        "Use Bolt for story and layout; never claim backend validated without tier three.",
        "PM who labels prototypes with known lies list.",
        "That pixel-perfect equals eng estimate accurate.",
        "Stakeholder sees Bolt demo; commits roadmap date.",
        "Significant underestimate; trust broken in planning.",
        "Recommends Bolt while warning limitation—dual message.",
        "Eng refuses estimate after Bolt demo; PM surprised.",
        "Politics of who misled whom.",
        "Demo disclaimer slide; explicit non-goals on prototype.",
        "Browser tools remain sales devices; engineering validation separate path."),
    row("Reflection Before Code", ep, g,
        "Best PM prototypes start with written reflection on user, risk, and decision—code without thought is expensive doodling.",
        "process", "Clarity is cheaper in markdown than in React.",
        "Thirty-minute reflection doc before any prompt; share for critique; then build.",
        "PM team with reflection template mandatory.",
        "That building is thinking; that speed requires skipping reflection.",
        "Hackathon culture; AI generates code instantly.",
        "Wrong product fast; beautiful dead ends.",
        "Prototyping guide emphasizes reflection in age of instant code.",
        "Repo full of orphans; no problem statement.",
        "Impatience from stakeholders.",
        "Pair reflection with kill criteria before opening IDE.",
        "Agents can draft reflection—human still signs problem worth solving."),
    row("Batching Prototype Work", ep, g,
        "Context-switching between Slack and prototype destroys flow—batch prototype blocks like deep work.",
        "productivity", "Partial attention produces partial prototypes that mislead.",
        "Two-hour minimum prototype blocks; notifications off; single decision target per block.",
        "PM calendar with prototype mornings defended by manager.",
        "That five-minute prompts between meetings count as building.",
        "Calendar Swiss cheese; nothing ships.",
        "Half-built demos shown prematurely; feedback noise.",
        "Advocates batching in async-first culture hostile to blocks.",
        "Always-on Slack; guilt about blocking time.",
        "Manager schedules over prototype block.",
        "Team norm: prototype blocks sacred; async responses delayed.",
        "Agents shorten build time—batching still matters for judgment."),
    row("Hyperspecific Prompts", ep, g,
        "Vague prompts produce generic UI—hyperspecific constraints on user, data, and edge cases are how PMs encode taste.",
        "craft", "Prompt specificity is product management in text.",
        "Include persona, data examples, error states, and non-goals in every build prompt.",
        "PM with prompt library tagged by product area.",
        "That model will infer your product sense.",
        "Demo looks like every other AI SaaS template.",
        "Stakeholders cannot tell your product apart; user test useless.",
        "More tools lower skill bar while raising taste bar.",
        "Copy generic prompt from blog.",
        "Frustration when output bland.",
        "Critique prompts like PRDs; iterate text before regenerating code.",
        "Prompt specificity becomes versioned spec—feeds evals later."),
    row("Checkpoint Rollback", ep, g,
        "Prototypes need git-like checkpoints—without rollback, one bad prompt destroys afternoon and morale.",
        "workflow", "Exploration requires reversible experiments.",
        "Save version before each major prompt; name checkpoints after hypothesis.",
        "PM using Lovable or Cursor history religiously.",
        "That undo is enough; that version control is eng-only.",
        "Broken state; cannot reproduce good version; demo tomorrow.",
        "Scramble rewrite; miss sleep; worse judgment.",
        "Easy tools hide need for discipline they still require.",
        "Never saves; blames tool.",
        "Anxiety about lost work.",
        "Teach checkpoint habit in onboarding; shared team naming convention.",
        "Agent sessions auto-checkpoint—PM skill becomes hypothesis labeling."),
    row("PRD Frontend-Only Trap", ep, g,
        "PRDs that specify only frontend lie about scope—AI makes frontend free while backend becomes the real schedule.",
        "planning", "Visible UI is not the product boundary.",
        "Prototype with fake data; document backend assumptions; eng reviews integration risks early.",
        "PM partnering eng on integration spike before commitment.",
        "That clickable PRD replaces technical discovery.",
        "CEO commits date from demo.",
        "Backend surprise doubles timeline; blame on eng bad faith.",
        "Frontend-only PRD warning in prototyping era when frontend is cheapest.",
        "PRD screenshots only; no API mention.",
        "Eng disengaged until too late.",
        "Integration appendix required on every PRD; eng signoff.",
        "PRDs shrink—replaced by prototype plus contract tests."),
    row("Lovable-Cursor Path", ep, g,
        "Typical path: start in Lovable for speed, graduate to Cursor when integration and files matter—graduation is skill not failure.",
        "workflow", "Tool graduation is expected lifecycle not indictment of first tool.",
        "Set graduation triggers: need real API, monorepo, or test suite.",
        "PM team celebrating Lovable to Cursor promotions in show-and-tell.",
        "That staying in browser builder is laziness.",
        "Premature Cursor use burns time on env issues.",
        "Stuck in Lovable past viability; or Cursor paralysis day one.",
        "Clear path vs identity attachment to first tool.",
        "Refuses to leave tool that raised them.",
        "Eng sneers at Lovable alumni.",
        "Mentor pairing for graduation week; checklist for export.",
        "Tools chain into pipelines—export between vendors standardizes."),
]

# --- Tal Raviv unfair PM (9) ---
ep, g = EP["unfair_pm"]
DATA += [
    row("Live Meeting Execution", ep, g,
        "The PM job is won in live meetings—not async docs—because alignment and politics move at the speed of human reaction.",
        "execution", "Documentation without presence loses to competitors who show up prepared and adaptive.",
        "Pre-brief outcomes, attend live, follow up in writing within an hour while memory is hot.",
        "PM who treats calendar as primary work surface not Slack.",
        "That great Notion wins wars; that async-first companies removed this truth.",
        "Hybrid schedules; dominant voices; exec skip-levels.",
        "Outmaneuvered in room; doc never read; surprise decisions.",
        "AI write not read while insisting meetings still matter.",
        "PM sends doc instead of attending; wonders why decision changed.",
        "Introverts told to perform extroversion; burnout.",
        "Meeting prep agent for scenarios; human still in room.",
        "Agents prep; humans negotiate—meeting skill premium rises."),
    row("Fifty-Nine Second Loom", ep, g,
        "Short Loom videos under sixty seconds replace long meetings for async clarity—brevity forces one decision per video.",
        "communication", "Respect for attention is a competitive advantage.",
        "Record one decision, one ask; link in Slack; no preamble apology tours.",
        "PM famous for crisp Looms leadership actually watches.",
        "That longer equals more professional; that everyone watches.",
        "Global team; timezone pain.",
        "Ten-minute rambles never played; rework requests multiply.",
        "Unfair work advice includes human video in AI era.",
        "PM writes essay thread instead of Loom.",
        "Camera shyness; perfectionism retakes.",
        "Template: context ten seconds, demo thirty, ask twenty.",
        "AI avatars generate Looms—authentic short human clips still trust winners."),
    row("Slack Morning Block", ep, g,
        "Protect first morning hours from Slack—or reactive PM work consumes the day before strategic work begins.",
        "productivity", "Availability defaults are enemy of depth.",
        "Delay Slack until post-deep-work block; set cultural expectation with manager.",
        "Team with documented quiet mornings.",
        "That responsiveness equals dedication; that DMs are emergencies.",
        "Cross-timezone pings at 6am; exec DMs culture.",
        "Always behind; no roadmap thinking; resentment.",
        "DMs are devil while newsletter lives on Slack ecosystem.",
        "Green dot obsession; anxiety when offline.",
        "Manager punishes slow response.",
        "Team charter for response SLAs; execs use email for true urgent.",
        "Agents triage Slack—human block still needed for hard calls."),
    row("Mini-PM Team", ep, g,
        "Unfair advantage comes from building a mini-team of allies—chief of staff energy, design partner, eng whisperer—not solo heroics.",
        "influence", "PM output is network output.",
        "Invest relationships before you need favors; reciprocate with clarity and credit.",
        "PM with informal coalition across functions.",
        "That merit alone drives decisions; that politics is optional.",
        "Reorg; hostile stakeholder; priority conflict.",
        "Isolated PM loses; coalition PM wins resource.",
        "Unfair play framed while preaching integrity—tension is real.",
        "Surprised when no eng sponsor.",
        "Disdain for politics labeled beneath me.",
        "Map stakeholders quarterly; deliberate reciprocity.",
        "Agent prep for stakeholders—human relationship still decisive."),
    row("DMs Devil Pattern", ep, g,
        "Decisions made in DMs create shadow alignment—public channels preserve fairness and audit trail.",
        "governance", "Private speed today becomes public conflict tomorrow.",
        "Push decisions to threads; summarize outcomes in writing in channel.",
        "Healthy org with DM for social not strategy.",
        "That DM is faster therefore better; that transparency slows you down.",
        "Exec prefers DM; culture of backchannels.",
        "Surprise launch objections; team learns decision late.",
        "Slack morning block vs DMs devil—same tool, different discipline.",
        "PM brags about exec DM access.",
        "Fear of public disagreement.",
        "Ask can we move this to channel; leader modeling.",
        "Agents summarize public channels—DM culture harder to audit."),
    row("Scrapbooking Career Capital", ep, g,
        "Collect proof of impact like scrapbook—metrics, quotes, artifacts—because unfair roles require self-advocacy no system provides.",
        "career", "If you do not record wins, they did not happen politically.",
        "Weekly scrapbook entry: outcome, evidence, lesson; use in reviews and interviews.",
        "PM with running brag doc shared selectively.",
        "That good work speaks for itself; that humility requires hiding impact.",
        "Layoff; manager change; promo committee.",
        "Forgotten contributions; weaker politician promoted.",
        "Unfair advice acknowledges system unfairness.",
        "No metrics; vague bullets.",
        "Discomfort boasting.",
        "Template shared in team; normalize evidence-based advocacy.",
        "Agents draft scrapbook from commits—human curates narrative."),
    row("AI Write Not Read", ep, g,
        "Use AI to produce artifacts others consume; do not use AI to consume instead of reading—thinking must stay human on inputs.",
        "ai_product", "Automation of output without input comprehension doubles risk.",
        "AI drafts memo; you read source data; you attend meeting; never AI-summary-only for decisions.",
        "PM with strict read-primary-sources rule.",
        "That summarization equals understanding.",
        "Huge doc drop; AI summary wrong on nuance.",
        "Bad decision from skipped reading; accountability still yours.",
        "AI productivity guide warns against AI over-read.",
        "Paste summary into leadership deck; caught in Q&A.",
        "Time pressure guilt.",
        "Block reading time before writing time in calendar.",
        "Market floods AI-written slop—human-read signal becomes trust marker."),
    row("Rest Hard Productivity", ep, g,
        "Unfair performance requires rest—chronic exhaustion makes you the slowest negotiator in the room.",
        "wellbeing", "Sustainable intensity beats performative hustle.",
        "Protect sleep and recovery like meeting blocks; sprint then recover.",
        "Senior PM modeling rest without apology.",
        "That burnout is badge of honor; that rest is for after promotion.",
        "Crunch; family guilt; layoff fear.",
        "Snap in meeting; poor judgment; health cost.",
        "Hustle culture critique inside hustle newsletter economy.",
        "Brags all-nighters; quality drops.",
        "Shame about boundaries.",
        "Team recovery days; no-meeting Friday real not fake.",
        "Agents reduce grunt work—rest becomes competitive edge not luxury."),
    row("Unfairness as Feature", ep, g,
        "The PM role is structurally unfair—accepting that lets you stop waiting for permission and play offense within ethics.",
        "mindset", "Fairness is not incoming; leverage is built.",
        "Stop expecting equitable process; invest in skills, coalition, and artifacts that change outcomes.",
        "Veteran PM mentoring juniors on system reality without cynicism.",
        "That HR process is neutral; that patience alone rewards.",
        "Bias; reorg politics; favorite exec projects.",
        "Bitterness paralysis; unethical shortcuts.",
        "Title says work unfairly—not cheat.",
        "Cynical gaming; ethical operators feel naive.",
        "Moral injury.",
        "Clear ethical bright lines; unfair within integrity.",
        "AI widens gap—ethical unfair players compound faster than waiters."),
]

# --- Jorge Mazal Duolingo (7) ---
ep, g = EP["duolingo"]
DATA += [
    row("Retention Before Acquisition", ep, g,
        "Duolingo reignited growth by fixing retention before buying traffic—acquisition on a leaky bucket is vanity.",
        "growth", "Retention is the honestest growth metric.",
        "Pause paid scale until core loop retention improves; reallocate to product quality and habit.",
        "Growth team subordinate to learning outcomes metric.",
        "That CAC solves everything; that viral marketing fixes bad product.",
        "Board pressure for user count; competitor ad spend.",
        "Burn on ads; churn hides; unit economics collapse.",
        "Classic growth vs Mazal retention-first turnaround story.",
        "Marketing celebrates installs; retention flat.",
        "Growth vs product blame game.",
        "Hold acquisition spend gate on CURR or retention threshold.",
        "AI personalization raises retention bar—acquisition without it wastes more."),
    row("CURR North Star", ep, g,
        "CURR—current user retention rate—became north star aligning product, marketing, and monetization on kept users not touched users.",
        "metrics", "One metric reduces religious wars if chosen correctly.",
        "Define CURR precisely; report weekly; tie experiments to CURR delta not vanity.",
        "Duolingo-style org with single hierarchical metric.",
        "That DAU alone drives stock story; that metrics are apolitical.",
        "Exec wants MAU for narrative; team optimizes wrong loop.",
        "Submetric gaming; short-term CURR hurt by monetization push.",
        "North star purity vs multiple competing goals at scale.",
        "Teams claim CURR win on definitional change.",
        "Metric politics in planning.",
        "Lock definition; audit changes; pair with learning outcome metric.",
        "AI products need CURR analog—session return not token count."),
    row("Intelligent Adaptation", ep, g,
        "Personalized difficulty and content path drove retention—one-size-fits-all lesson is operational malpractice.",
        "personalization", "Learning products must adapt faster than user boredom.",
        "Invest in adaptation engine; A/B path algorithms; measure learning not just time-on-app.",
        "Data science embedded in curriculum squad.",
        "That content library size equals quality; that teachers scale linearly.",
        "Model costs; cold start for new languages.",
        "Generic path; bored advanced users; overwhelmed beginners quit.",
        "Human teachers vs AI adaptation—both needed at scale.",
        "Static course envy from competitors.",
        "Pedagogy vs ML team conflicts.",
        "Expose adaptation visibly so users trust system.",
        "LLM tutoring makes adaptation table stakes—static courses die."),
    row("Leaderboards for Strangers", ep, g,
        "Social competition works among strangers with similar levels—not friends only—because embarrassment dynamics differ.",
        "social", "Social design must match relationship graph reality.",
        "League strangers not friend leaderboard; reset cycles to reduce demotivation.",
        "Game designers tuning league segmentation weekly.",
        "That Facebook friend graph is required for virality.",
        "Privacy backlash on friend compare.",
        "Demotivated users quit; toxic competition.",
        "Stranger leagues success vs schools banning competitive ranking.",
        "Users cheat leagues; bots in leaderboard.",
        "Parents vs growth on child competition.",
        "Segment leagues; anti-cheat; opt-out paths.",
        "AI opponents in leagues—new fairness debates emerge."),
    row("Protect Notification Channel", ep, g,
        "Notifications are a scarce trust channel—over-notification trains ignore and kills retention lever.",
        "engagement", "Every push is a withdrawal from a finite trust account.",
        "Cap frequency; personalize timing; measure uninstall and mute not just open rate.",
        "Growth team with notification budget per user per week.",
        "That more reminders equals more learning.",
        "Quarter push revenue target.",
        "Notification blindness; brand annoyance; OS-level mute.",
        "Streak mechanics depend on notifications—tension with protection.",
        "Open rate up; retention down.",
        "User backlash on TikTok.",
        "Model optimal send time; kill campaigns that spike unsubscribes.",
        "AI personalized nudges can restore trust or destroy faster."),
    row("Streak Compounding", ep, g,
        "Streaks compound habit—but also create anxiety and brittle motivation—operational balance required.",
        "habit", "Loss aversion drives return visits until it drives shame quit.",
        "Streak freeze; repair mechanics; pair streak with real learning minutes.",
        "Live ops team monitoring streak-induced churn cohorts.",
        "That infinite streak growth is always good.",
        "Competitor copies streak without repair.",
        "Burnout users leave permanently; negative press on dark patterns.",
        "Streak hero story vs mental health criticism.",
        "Users cheat timezone; support tickets explode.",
        "Ethics vs growth OKR fight.",
        "Streak ethics review; transparent mechanics.",
        "AI coaches may replace dumb streaks with competence streaks."),
    row("Big Swings Plus Optimize", ep, g,
        "Duolingo balance: big swings on new bets while optimizing core—both required; either alone stalls.",
        "strategy", "Exploration and exploitation are concurrent jobs not phases.",
        "Portfolio budget: percent resources on swings; percent on CURR optimization; review quarterly.",
        "Leadership team with explicit swing list and owner.",
        "That optimization is boring so skip it; that swings excuse core neglect.",
        "Investor wants new product line; core decaying.",
        "Swing fails; core weakened; no floor.",
        "Turnaround story includes both discipline types.",
        "All swings no ops; or all ops no innovation.",
        "Credit fights between teams.",
        "Swing postmortems; core regression tests on CURR.",
        "AI enables more swings—without optimization discipline companies die faster."),
]

assert len(DATA) == 78, len(DATA)

out = Path(__file__).parent / "_newsletter_oi_data.py"
lines = ['"""Operational intelligence tuples for Lenny newsletters (78 patterns)."""', "", "DATA = ["]
for t in DATA:
    lines.append("    " + repr(t) + ",")
lines.append("]")
lines.append("")
out.write_text("\n".join(lines), encoding="utf-8")
print(f"Wrote {len(DATA)} tuples to {out}")
