#!/usr/bin/env python3
"""Generate operational-intelligence-batch2.json."""

import json
from collections import Counter

patterns = []


def add(ep, guest, name, quote, cat, belief, op, arch, hidden, pres, fail, con, sig, emo, adapt, ai):
    patterns.append({
        "pattern_name": name,
        "source_episode": ep,
        "source_guest": guest,
        "source_quote_or_context": quote,
        "category": cat,
        "core_belief": belief,
        "operational_pattern": op,
        "organizational_archetype": arch,
        "hidden_assumptions": hidden,
        "pressure_scenarios": pres,
        "failure_modes": fail,
        "contradictions": con,
        "behavioral_signals": sig,
        "emotional_political_dynamics": emo,
        "operational_adaptations": adapt,
        "ai_era_implications": ai,
    })


# --- BORIS CHERNY ---
ep, g = "Boris Cherny", "Boris Cherny"

add(ep, g, "Mission Over Product Excitement",
    "What I really missed about Ant was the mission... even if it's building a really cool product, it's just not really a substitute for that.",
    "leadership",
    "Mission-fit beats product excitement for sustained builder energy.",
    "When evaluating job moves, weight mission alignment above product novelty; expect fast reversals when mission gap appears.",
    "Senior IC/founder choosing between labs and product companies",
    ["Great products compensate for weak mission", "Two-week trials reveal culture fit"],
    ["Tempting Cursor-style product pull", "Burnout on technically exciting but empty work"],
    ["Bouncing between top AI companies", "Staying for comp while disengaged"],
    ["Claims mission-first but optimizes for product hype"],
    ["Quiet disengagement from safety rituals", "Over-indexing on external launches"],
    ["Shame about leaving quickly", "Loyalty pressure from new teammates"],
    ["Write mission criteria before entertaining offers", "Use short trials with explicit mission checkpoints"],
    ["AI talent war makes mission the retention moat when models commoditize"])

add(ep, g, "Under-Resource To Force Agentification",
    "You want to under-resource things a little bit at the start... if you have one engineer on a project, they're forced to Claude-ify.",
    "execution",
    "Constraint plus great engineers produces disproportionate agent leverage.",
    "Staff lean squads on new bets; pair unlimited tokens with small headcount; optimize cost only after idea proves out.",
    "CTO scaling AI-native engineering",
    ["More headcount always speeds shipping", "Token spend is waste pre-PMF"],
    ["Competitive coding market", "Board pressure to cut AI spend early"],
    ["Over-hiring before workflows exist", "Premature model downgrades killing experiments"],
    ["Preaches lean teams while company headcount grows 4x"],
    ["Many engineers on one agentic feature", "Leaders blocking token budgets"],
    ["Fear that AI makes headcount look wasteful"],
    ["Unlimited tokens as hiring perk", "Single-owner projects with explicit speed KPIs"],
    ["Default org design becomes small teams orchestrating many agents"])

add(ep, g, "Terminal Form Factor For Model Velocity",
    "The model is improving so quickly, we felt there wasn't really another form factor that could keep up... the terminal was the only idea that I had.",
    "product",
    "Fastest-improving models need the least prescriptive UI shell.",
    "Prefer minimal, composable surfaces (CLI/terminal) until model capabilities stabilize; add IDE layers after workflow clarity.",
    "AI coding product team racing model releases",
    ["Users need polished IDE on day one", "Terminal is too alien for adoption"],
    ["Enterprise buyers demand familiar UI", "Internal skeptics after two-like launches"],
    ["Heavy UI investment obsoleted quarterly", "Chasing every competitor form factor"],
    ["Ships terminal while marketing polished apps"],
    ["Power users in CLI; mass market in GUI wrappers"],
    ["Design vs infra tension on form factor"],
    ["Multi-surface distribution once behavior stabilizes", "DAU charts from week one per Ben Mann advice"],
    ["Agent UIs stay thin; value migrates to orchestration and integrations"])

add(ep, g, "Feedback Velocity As Product Moat",
    "If you make people feel heard, then they want to contribute... now Claude does a lot of the work on internal feedback channels.",
    "product",
    "Tight feedback loops beat roadmap certainty in agentic products.",
    "Instrument internal feedback firehose; fix or agent-fix within minutes early on; point agents at Slack/telemetry for ideation.",
    "Head of fast-moving devtool with vocal power users",
    ["Roadmaps should be quarterly and fixed", "PMs must gate all feedback"],
    ["Viral growth without support capacity", "Model releases breaking workflows"],
    ["Feedback black holes", "Humans become review bottleneck only"],
    ["Celebrates user voice while prioritizing stealth features"],
    ["Internal channel quieting", "PMs defensive about auto-PRs from agents"],
    ["Fear PM role obsolete", "Pride in manual triage"],
    ["Cowork/agents triage feedback into PRs", "Public fix streaks to encourage more signal"],
    ["PM work shifts from prioritization queues to taste and strategy"])

add(ep, g, "Exponential Planning At Anthropic",
    "We really just think in exponentials... all I did was trace the line on percent of code written by Claude.",
    "strategy",
    "Linear intuition systematically under-forecasts AI adoption curves.",
    "Force exponential scenarios in planning; personal dogfood to 100% AI code before assuming industry lag.",
    "Lab leadership forecasting dev tool impact",
    ["S-curves cap at partial adoption", "Regulation will slow exponentials"],
    ["Board asks for conservative forecasts", "Engineers dismiss year-end predictions"],
    ["Planning as if 20% AI code is ceiling", "Under-investing in safety for agentic tools"],
    ["Public exponential talk; internal linear resourcing"],
    ["Gasps at conferences then slow internal migration"],
    ["Anxiety about sounding alarmist"],
    ["Personal 100% AI coding as credibility", "Publish leading indicators not lagging surveys"],
    ["Organizations that don't plan exponentially get surprised by capacity and security needs"])

add(ep, g, "Layer-Under-Layer Engineering Literacy",
    "To do good work you really have to understand the layer under the layer... with AI, you have to understand the model.",
    "execution",
    "Effective builders still descend one abstraction level.",
    "Onboard via month hacking plus post-training exposure; expect staff to debug via agents but understand runtime/model limits.",
    "Engineering org mixing researchers and product builders",
    ["Vibe coding removes need to understand systems", "Only researchers need model knowledge"],
    ["Rapid model upgrades", "Legacy engineers debugging manually"],
    ["Blind trust in agent output on prod", "Skills atrophy celebrated"],
    ["New grads out-agent veterans on novel bugs"],
    ["Seniors clinging to heap snapshots", "Researchers disconnected from product pain"],
    ["Status from low-level mastery"],
    ["Rotate engineers through post-training", "Celebrate agent-first debugging wins"],
    ["Understanding models becomes core eng literacy like compilers once were"])

add(ep, g, "Printing Press Literacy Analogy",
    "Literacy went from sub-1% scribes to 70% over 200 years after the printing press... programming may democratize similarly.",
    "culture",
    "Tool revolutions expand who can participate, not eliminate experts overnight.",
    "Frame AI coding as literacy expansion; invest in education/time-for-learning, not gatekeeping syntax.",
    "Industry leader communicating AI societal impact",
    ["Everyone codes next year", "Engineers disappear immediately"],
    ["Backlash against non-traditional builders", "Schools slow to adapt curricula"],
    ["Elite panic about status loss", "Policy fights over credentialing"],
    ["Democratization rhetoric; hiring still credentialist"],
    ["Artisan hand-coders as identity"],
    ["Nostalgia among veteran engineers", "Policy anxiety about democratized building"],
    ["Pair historical analogs with safety work", "Make building delightful to widen funnel"],
    ["Builder population explodes; expert role shifts to orchestration and judgment"])

add(ep, g, "Builder Title Collapse",
    "By the end of the year everyone is going to be a product manager, and everyone codes... software engineer title will be replaced by builder.",
    "org_design",
    "Role boundaries dissolve when execution cost drops.",
    "Train hybrid builders; expect PM/eng/design overlap; staff for outcomes not function silos.",
    "Tech company re-orging around agents",
    ["Titles protect compensation bands", "Specialization always efficient"],
    ["Union of crafts resisting merge", "Managers unclear on career ladders"],
    ["Title inflation without skill merge", "PMs avoiding code accountability"],
    ["Everyone claims builder; few ship end-to-end"],
    ["Territorial design/eng/PM fights"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Shared agent tooling across functions", "Comp bands tied to impact not craft"],
    ["Performance reviews based on shipped outcomes and agent leverage"])

# --- BRIAN HALLIGAN ---
ep, g = ("Sequoia CEO coach: Why it's never been easier to start a company, "
         "and never been harder to scale one | Brian Halligan (co-founder, HubSpot)"), "Brian Halligan"

add(ep, g, "Constructive Dissatisfaction Operating Mode",
    "Perpetual state of constructive dissatisfaction... always a little bit dissatisfied with where they are, very focused on the end state.",
    "leadership",
    "Restless dissatisfaction paired with humility beats victory laps.",
    "Coach CEOs to stay future-anchored; celebrate wins briefly; channel dissatisfaction into exec-team quality not self-flagellation.",
    "Sequoia-backed hypergrowth CEO",
    ["Content CEOs scale better", "Dissatisfaction equals toxicity"],
    ["Post-IPO complacency", "Peer comparison at CEO tables"],
    ["Performative hustle without learning", "Cynicism about wins"],
    ["Public humility; private blame"],
    ["Avoiding retros", "Chasing next round narrative only"],
    ["Coach normalizes dissatisfaction as feature"],
    ["Kids vs adults CEO tables for stage-fit problems", "Peer misery loops on hard feedback"],
    ["AI multiplies execution options—dissatisfaction must focus which bets not to take"])

add(ep, g, "Spiky Executive Over Consensus Hire",
    "Almost every time we hired the three out of four... we went with the spikier people, people with weaknesses who would challenge stuff.",
    "hiring",
    "Executive impact comes from spikes and challenge, not balanced mediocrity.",
    "Score interviews 1–4; prefer polarized panels over uniform 3/4; shrink panel size to four.",
    "CEO hiring first C-suite at ~50–500 employees",
    ["Avoid weakness on exec team", "More interviewers increase accuracy"],
    ["Founder fear of being challenged", "Board wants brand-name safe hires"],
    ["Hiring uniform executives", "Eight-person panels averaging to bland"],
    ["Claims to want challengers; punishes pushback"],
    ["Panel scores cluster at 3", "Avoids references that surface spikes"],
    ["Ego protection on founder decisions"],
    ["Parker Conrad board-deck interview", "Blind references with rehire scales"],
    ["AI resumes hide spikes—interviews must test live challenge and taste"])

add(ep, g, "Blind Reference Enthusiasm Test",
    "Would you enthusiastically rehire this person for that role? ... on a scale of one to ten, how likely you'll try to rehire them back.",
    "hiring",
    "Reference quality is revealed by question difficulty not checkbox strengths.",
    "Probe references with rehire/top-percentile questions; detect box-checking vs genuine investigation.",
    "Founder doing C-level reference calls",
    ["References are legal formalities", "Candidates always pick friendly refs"],
    ["Rushed exec search", "Investor intro refs are unbiased"],
    ["Accepting strengths/weaknesses lists", "Ignoring lukewarm enthusiasm"],
    ["Founder hears only positives", "VC already decided"],
    ["Fear of killing a 'star' hire"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Train execs on reference scripts", "Decline refs when decision pre-made"],
    ["AI background checks don't replace human rehire probes"])

add(ep, g, "Big Company Impedance Mismatch",
    "Massive impedance mismatch when you hire Microsoft/Salesforce exec at 50 employees... 100% attrition on those folks.",
    "hiring",
    "Prestige resumes misfit startup chaos tolerance.",
    "Avoid logo hires expecting mature processes; favor homegrown or true startup scar tissue.",
    "Scaling startup tempted by FAANG VPs",
    ["Big-co playbooks transfer", "Fancy title fixes execution"],
    ["Board pushes adult supervision", "Founder imposter syndrome"],
    ["McKinsey cohorts as saviors", "Repeated logo hire waves"],
    ["Founder blames hire not fit"],
    ["Execs surprised by lack of ops", "Teams split on outsider"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Red Sox model: homegrown core plus few free agents"],
    ["AI lets small teams output big-co volume—less need for big-co managers"])

add(ep, g, "Optionality Tax In Fast Cycles",
    "Massive tax in optionality when you can move this fast... planning cycles now three months.",
    "strategy",
    "Speed punishes indecision and one-way door paralysis.",
    "Shorten planning horizons; walk through one-way doors faster; avoid second-act hops before beachhead depth.",
    "CEO with AI-accelerated roadmap surface area",
    ["Keeping options open is prudent", "Annual planning still works"],
    ["Competitor launches weekly", "Team proposes many parallel bets"],
    ["CEO as bottleneck on decisions", "False second acts for narrative"],
    ["Talks speed while hoarding optionality"],
    ["Quarterly planning theater", "OpenAI/Gemini distraction envy"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Peer tables to practice faster decisions", "Explicit kill criteria for side bets"],
    ["More projects possible—optionality tax rises without ruthless focus"])

add(ep, g, "DRI Religion At Scale",
    "If you want to kill a plant, have two people water it... adults' table zealots on DRI.",
    "execution",
    "Cross-functional outcomes require single accountable owner with authority.",
    "Name one DRI per pilot/process; give power across silos; avoid co-ownership on critical metrics.",
    "Scaled company running enterprise pilots",
    ["Shared ownership increases quality", "Committees reduce risk"],
    ["Pilot failures without postmortem", "Sales/SE/PM each think other owns"],
    ["DRIs without authority", "Matrix confusion"],
    ["Everyone in meetings; nobody decides"],
    ["Political diffusion of blame"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Pilot playbooks with named DRI", "Escalation rights across functions"],
    ["Agent handoffs still need human DRI or brooms flood the castle"])

add(ep, g, "Eat The Shit Sandwich Whole",
    "When you have to eat a shit sandwich, don't nibble... rip the Band-Aid off on layoffs and bad news.",
    "leadership",
    "Partial painful actions compound trauma.",
    "Do single decisive corrections; pair with 'next play' culture after errors.",
    "CEO facing valuation reset or outage",
    ["Small layoffs are kinder", "Delay bad news for morale"],
    ["Bubble deflation", "Major outage customer anger"],
    ["Death by repeated layoffs", "Under-communicating crisis"],
    ["Public empathy; private nibbling"],
    ["Team PTSD from rolling cuts"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Coach Krzyzewski next-play slides", "Over-correct after crisis then stabilize"],
    ["AI efficiency may force one clean reset not rolling trims"])

add(ep, g, "LOCK CEO Selection Rubric",
    "Lovable, Obsessed, Chip on shoulder, Knowledgeable... student of the game.",
    "hiring",
    "Founder quality is multi-trait pattern match not charisma alone.",
    "Screen for followership, obsession depth, domain knowledge, learning velocity; add student mindset for scaling skills.",
    "VC evaluating founder CEOs",
    ["Anyone can be CEO with effort", "Charisma equals lovable"],
    ["Hot market FOMO", "Founder six months into problem"],
    ["Picking resume over obsession", "Ignoring chip as red flag"],
    ["LOCK talk for investability not coaching"],
    ["Founders perform learning in pitches"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Five-tool CEO rare but rising with AI"],
    ["AI fills skill gaps but not lovable/trust/craft obsession"])

# --- SHERWIN WU ---
ep, g = "Sherwin Wu V2", "Sherwin Wu"

add(ep, g, "Codex Fleet Tech Lead Model",
    "IC engineers are becoming tech leads... managing fleets and fleets of agents.",
    "execution",
    "Engineering job is parallel agent orchestration not typing.",
    "Run 10–20 agent threads; steer/review; treat prompts as incantations with senior judgment.",
    "OpenAI API platform engineering team",
    ["More agents always better", "Junior engineers can't orchestrate"],
    ["Agent failures block releases", "Review debt from PR explosion"],
    ["Mickey Mouse broom flood", "Ignoring stuck agents"],
    ["PR volume up 70% for power users"],
    ["Stress when agents idle", "Seniors babysitting juniors' agents"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["SICP wizard metaphor for training", "No escape hatch experiments"],
    ["Sorcerer's apprentice risk scales with autonomous agents"])

add(ep, g, "No Escape Hatch Codex Experiment",
    "Team maintaining 100% Codex-written codebase without rolling up sleeves manually.",
    "execution",
    "Forcing agent-only path surfaces context and documentation gaps.",
    "Run no-manual-code pilots; encode tribal knowledge into skills/md/comments when agents fail.",
    "Platform team pushing agent limits",
    ["Humans can always patch", "Agents ready for full autonomy"],
    ["Stuck features without manual debug", "Production incidents"],
    ["Reverting to manual secretly", "Blaming model not context"],
    ["Publishing learnings from blocked tasks"],
    ["Frustration when agent won't comply"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Blog best practices from pilot", "Expand repo context artifacts"],
    ["Teams that never remove escape hatch won't learn agent-native workflows"])

add(ep, g, "Agent Failure Is Context Failure",
    "When the coding agent is not doing what you want, it's usually a problem with context.",
    "execution",
    "Underspecified context dominates model capability gaps.",
    "Add docs, structure, skills files; treat fixes as information architecture not model swaps.",
    "Engineer debugging agent misfires",
    ["Bigger model fixes everything", "Prompt hacks replace specs"],
    ["Legacy tribal knowledge in heads", "Tight deadlines skip documentation"],
    ["Model hopping spiral", "Blaming tool vendor"],
    ["Repeated same agent mistake patterns"],
    ["Shame about 'needing docs'"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Context engineering as sprint work", "Skills per repo/domain"],
    ["Context engineering becomes primary senior eng skill"])

add(ep, g, "Automate Annoying Toil First",
    "We hand to models the things that annoy us... code review was one of the worst things for me.",
    "execution",
    "Delegate loathed engineering toil to agents first for adoption.",
    "100% Codex PR review; automate lint/CI fixes; collapse deploy friction.",
    "EM who hated reviews owning newsfeed at Quora",
    ["AI must start with greenfield features", "Review requires human-only judgment"],
    ["PR tsunami", "Trust anxiety on auto-merge"],
    ["Circular self-review without human spot checks"],
    ["Review time drops 10–15 min to 2–3"],
    ["Relief among engineers", "Purists resist auto-review"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Dogfood internal models", "Variant models for second opinion"],
    ["Review and CI toil automated before greenfield coding"])

add(ep, g, "Build For Future Models",
    "Build for where the models are going, not where they are today... this is the worst the models will ever be.",
    "strategy",
    "Scaffolding has short half-life; bet on capability curves.",
    "Minimize durable scaffolding; ship for next-quarter models; treat customer requests skeptically when field moves weekly.",
    "Platform product leader in fast-moving model market",
    ["Heavy bespoke scaffolding", "Customer-driven short-term only"],
    ["Model release obsoletes product", "Competitor leapfrog"],
    ["Over-fit to today's failures"],
    ["Listening to customers is always right"],
    ["Kevin Weil quote as planning anchor", "Reduce scaffolding each release"],
    ["FOMO on shipping for today's customers"],
    ["Reduce scaffolding each release", "Internal no-escape-hatch pilots"],
    ["Product orgs that listen only to today's users under-shoot"])

add(ep, g, "Surgeon Manager Metaphor",
    "Spend more than 50% of your time with top 10% performers... manager as scalpel supplier in surgery room.",
    "leadership",
    "Manager leverage is unblocking top performers not equal time spread.",
    "Majority time on top decile; pre-clear organizational blockers; anticipate needs.",
    "EM at API platform powering AI economy",
    ["Fair time split is just", "Low performers need most help"],
    ["Top performers don't need managers", "Reorgs distract"],
    ["Stars blocked by process", "Manager as meeting filler"],
    ["Manager in Slack/Notion clearing path"],
    ["Resentment from middle tier"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["AI to scan org docs for blockers", "Pre-stage approvals and decisions"],
    ["Manager span increases when AI handles context gathering"])

add(ep, g, "Top Performer Spread Widens",
    "Codex empowers top performers... broader spread in team productivity.",
    "org_design",
    "AI amplifies agency; distribution widens.",
    "Identify high-agency engineers; let them experiment publicly; share practices org-wide.",
    "Platform EM during Codex adoption",
    ["AI lifts all equally", "Mean productivity is right metric"],
    ["Performance review politics", "Tool access inequality"],
    ["Middle cohort disengages", "Hero dependency"],
    ["70% more PRs from power users"],
    ["Envy of codex-pilled peers"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Knowledge sharing sessions from pilots", "Unblock stars first"],
    ["Comp and leveling must account for 10x individuals"])

add(ep, g, "One-Person Billion Startup Second-Order Effects",
    "Enable one-person billion-dollar startup... hundred other small startups building bespoke software.",
    "strategy",
    "Extreme leverage fragments tooling into vertical micro-SaaS.",
    "Expect startup boom, vertical AI tools, B2B golden age; VC returns may concentrate in platforms.",
    "OpenAI platform leader forecasting ecosystem",
    ["Winner-take-all only", "Support scales linearly with revenue"],
    ["Founder does everything in-house"],
    ["Micro-ISVs per workflow", "Outsourced support stacks"],
    ["Lenny's newsletter support objection vs bespoke vendors"],
    ["Platform players capture infra value"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Build for micro-customer segments", "Partner with vertical one-person vendors"],
    ["Distribution and trust become scarcer than build capability"])

# --- LAZAR JOVANOVIC ---
ep, g = ("The rise of the professional vibe coder (a new AI-era job) | "
         "Lazar Jovanovic (Professional Vibe Coder)"), "Lazar Jovanovic"

add(ep, g, "Hire Yourself Via Build In Public",
    "You don't need a company to hire you. You can hire yourself as a professional vibe coder first.",
    "career",
    "Demonstrated public shipping beats waiting for role creation.",
    "Publish builds; create demand; let companies retroactively define the job around you.",
    "Non-technical builder aspiring to full-time vibe role",
    ["Need official title first", "Portfolio must be traditional code"],
    ["No credential gatekeepers", "Tool churn"],
    ["Only talking not shipping", "Chasing certifications"],
    ["Public templates and integrations shipped"],
    ["Community remix counts"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Cross-department rover model", "Ideas-to-production latency as KPI"],
    ["Professional vibe coder becomes formal headcount category"])

add(ep, g, "Positive Delusion Without Ignorance",
    "Positively delusional that everything is possible until proven wrong... but self-aware you must get better.",
    "mindset",
    "Naivete unlocks builds expertise prevents; both required.",
    "Attempt 'impossible' builds; pair with learning from agent output not syntax.",
    "Non-technical Lovable power user",
    ["Experts know what's impossible", "Delusion equals recklessness"],
    ["Security incidents from slop", "Scale surprises"],
    ["Shipping unsafe prod", "Never reading agent reasoning"],
    ["Chrome extensions from 'wrong' stack"],
    ["Technical peers explain why not"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["80% planning chat / 20% execute", "Agent output as curriculum"],
    ["Ignorance advantage shrinks as models improve—judgment remains"])

add(ep, g, "Clarity Over Coding Speed",
    "Coding is not the problem we're solving... the problem is clarity.",
    "execution",
    "Wrong optimization target is execution velocity not spec quality.",
    "Spend majority time planning/chatting; treat AI as co-founder educator; read agent narratives.",
    "Professional vibe coder across departments",
    ["More prompts equals faster", "Code view is source of truth"],
    ["Context window overload", "Vague wishes"],
    ["13-foot genie outcomes", "Slop cascades"],
    ["Long chat sessions before build", "Three-wish batching"],
    ["Frustration at 'you know what I mean'"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Genie analogy for context limits", "Structured wish templates"],
    ["Winners optimize clarity and taste; tools commoditize typing"])

add(ep, g, "Build Versus Buy Inversion",
    "If enterprise setup takes two hours, I'll build it myself faster.",
    "execution",
    "Builder breakeven vs SaaS moves sharply toward build for custom stacks.",
    "Default to custom internal tools when integration cost exceeds hours-to-ship with AI.",
    "Fast-growth startup internal tools owner",
    ["Buy always safer", "IT prefers vendors"],
    ["Security review delays", "Unique metrics needs"],
    ["Perpetual shelfware", "Shadow IT rebuilds"],
    ["Feature adoption dashboards custom-built"],
    ["Departments queue for Lazar"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Rover across growth/GTM/enterprise", "Template libraries for external proof"],
    ["Every function gets a vibe coder; SaaS consolidates to niches"])

add(ep, g, "AI Amplifies Judgment Not Ignorance",
    "AI is an amplifier. If you don't know what you're doing, you produce garbage faster.",
    "product",
    "Tool leverage multiplies prior clarity and taste.",
    "Invest in domain judgment, security awareness, quality bar before scaling prompts.",
    "Company hiring first vibe coder",
    ["AI removes need for expertise", "Anyone can ship prod day one"],
    ["Slop outages", "Brand damage from bad public builds"],
    ["High remix low retention", "Internal tools break silently"],
    ["Quality merch stores vs broken flows"],
    ["Engineers dismiss vibe outputs"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Pair vibe coders with security review hooks", "Education via agent explanations"],
    ["Garbage faster becomes catastrophic at agent parallelism"])

add(ep, g, "Calligraphy Coding Future",
    "Coding is going to be like calligraphy... rare art.",
    "culture",
    "Manual coding becomes craft signal not default production.",
    "Don't optimize careers for hand-coding; optimize for product outcomes and orchestration.",
    "Aspiring builders fearing code gate",
    ["Must master syntax first", "Hand code always more reliable"],
    ["Artisan pride resistance", "Hiring still LeetCode-heavy"],
    ["Performative manual commits"],
    ["Weekend C++ by choice on team"],
    ["Identity tied to syntax beauty"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Celebrate outcomes not LOC", "Keep craft optional"],
    ["Roles converge to builder; calligraphy coders niche"])

add(ep, g, "Cross-Department Ideas Role",
    "It's an ideas role... step in when people have ideas but not bandwidth.",
    "org_design",
    "Centralized builder bandwidth unlocks org creativity.",
    "Embed rover with high velocity mandate across growth/GTM/community/enterprise.",
    "Fastest-growing startup without enough builders",
    ["Ideas belong in product team only", "Random AI experiments scattered"],
    ["Backlog of dept requests", "Quality bar debates"],
    ["Every team hires own vibe coder"],
    ["Elena growth ideas shipped fast"],
    ["Departments compete for Lazar time"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Start in growth; expand on proof", "Templates as reusable assets"],
    ["Head of vibe coding or builder pool becomes standard"])

add(ep, g, "Non-Technical Advantage",
    "People like me don't know they're not supposed to be building X... that's how we build it.",
    "mindset",
    "Expertise can preclude attempts models now make possible.",
    "Invite naive builders; delay technical naysaying until after attempt.",
    "Community challenging 'impossible' on Lovable",
    ["Stack constraints are laws", "Only engineers innovate"],
    ["Failed attempts waste time", "Security always blocks"],
    ["Desktop apps and Chrome extensions shipped"],
    ["Technical explainers in threads"],
    ["Respectful skepticism vs curiosity"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Community challenges as R&D", "Promote impossible asks"],
    ["Companies pair naive builders with senior reviewers not gatekeepers"])

# --- DR BECKY KENNEDY ---
ep, g = ("A child psychologist's guide to working with difficult adults | "
         "Dr. Becky Kennedy"), "Dr. Becky Kennedy"

add(ep, g, "Behavior Signals Missing Skill",
    "When you look at bad behavior, the actual problem is someone doesn't have the skill they need to manage something happening internally.",
    "leadership",
    "Misbehavior is skill deficit not identity verdict.",
    "Diagnose internal skill gaps before character attacks; teach regulation/cooperation skills at work as with kids.",
    "Leader dealing with 'difficult' reports",
    ["Bad behavior equals bad person", "Adults should already have skills"],
    ["High-stress quarters", "Cross-functional conflict"],
    ["Labeling lazy/disengaged", "Skipping skill coaching"],
    ["HR as punishment path only"],
    ["Shame when labeled", "Leader frustration"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Good Inside principles across systems", "Training on emotional regulation"],
    ["AI won't fix adults who lack skills—coaching still core"])

add(ep, g, "Good Inside At Work",
    "Separate behavior and identity... quickest way to unproductive conversation is losing sight someone's good inside.",
    "leadership",
    "Identity safety enables honest performance conversations.",
    "Frame feedback on behaviors; maintain respect for person's core goodness.",
    "Manager with chronically late report",
    ["Late equals lazy narrative", "Radical candor without care"],
    ["Performance plans", "Public criticism"],
    ["Assumption cascades", "Gossip about character"],
    ["Defensive spirals in 1:1s"],
    ["Fear of being 'bad employee'"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Most Generous Interpretation habit", "Behavior-specific feedback scripts"],
    ["Automated surveillance without goodness lens worsens trust"])

add(ep, g, "Repair As Trust Multiplier",
    "Secure attachment isn't getting it right all the time—it's the presence of repair.",
    "leadership",
    "Accountable return after rupture builds more trust than faux perfection.",
    "After harsh meeting: own tone, impact, plan; don't defend; 'perfect is creepy.'",
    "Leader who interrupted report in meeting",
    ["Leaders must be right", "Apology shows weakness"],
    ["High-stakes exec reviews", "Parenting-style shame triggers"],
    ["Avoiding follow-up", "Over-apologizing without change"],
    ["Team relaxes post-repair", "Run-on defensive conversations drop"],
    ["Relief and renewed cooperation"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Company mantra 'perfect is creepy'", "Model repair publicly"],
    ["Async AI slights need human repair loops too"])

add(ep, g, "Connect Before Correct",
    "Connection forms a bridge so they can walk back to your world to act in shared interest.",
    "leadership",
    "Correction without connection fails as coercion.",
    "Join person's reality briefly (taxes-on-couch vs demands); then invite joint problem-solving.",
    "Manager needing report to finish urgent work",
    ["Skip to task immediately", "Connection as manipulation prelude"],
    ["End-of-quarter push", "Remote disconnection"],
    ["Transactional check-ins", "Kids/partners 'don't listen'"],
    ["Eyes roll at forced rapport"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Explicit rituals and scripts to operationalize the pattern"],
    ["Genuine 30 seconds presence", "Acknowledge their context first"],
    ["Radical candor with real care", "Don't use AI to fake connection"])

add(ep, g, "Boundaries Are Your Actions",
    "Boundaries are what you tell someone else you will do, and it requires the other person to do nothing.",
    "leadership",
    "Requests are not boundaries; only self-controlled consequences are.",
    "State what you will do if pattern continues; stop expecting them to change voluntarily.",
    "Leader tolerating missed commitments",
    ["If they cared they'd comply", "Boundaries are ultimatums"],
    ["Chronic deadline slips", "Scope creep"],
    ["Repeated 'please fix' emails"],
    ["Resentment without stated boundary"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Explicit rituals and scripts to operationalize the pattern"],
    ["Scripts: I will X if Y continues", "Train managers on boundary vs request"],
    ["Clear boundaries reduce AI ping-pong escalation loops"])

add(ep, g, "Resilience Over Happiness Culture",
    "Resilience over happiness... people who can say this is hard and I can do hard things.",
    "culture",
    "Optimize for capacity to endure difficulty not comfort maximization.",
    "Celebrate struggle tolerance; avoid fixing all discomfort; build sturdy teams.",
    "Exec building culture during hard pivot",
    ["Happy employees are productive", "Hard messages harm culture"],
    ["Layoffs", "Intense product bets"],
    ["Toxic positivity", "Burnout from false cheer"],
    ["Team naming hard things openly"],
    ["Fear of looking weak"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Sturdy leadership training", "Pair ambition with support"],
    ["AI accelerates pace—resilience required to avoid brittleness"])

add(ep, g, "Sturdy Leader Presence",
    "Your goal as a leader is to become sturdy.",
    "leadership",
    "Steadiness under others' dysregulation is the intervention.",
    "Regulate self first; don't match panic; hold container for hard emotions.",
    "Founder during team meltdown",
    ["Leader must fix feelings", "Sturdiness equals detachment"],
    ["Crisis weeks", "Difficult adult tantrums in exec room"],
    ["Leader escalates matching energy", "Team loses anchor"],
    ["Calm voice amid storm", "Predictable responses"],
    ["Safety to be honest"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Coach leaders on nervous system regulation", "Model sturdiness after mistakes via repair"],
    ["Leaders sturdy enough to direct agents without panic spirals"])

add(ep, g, "Most Generous Interpretation",
    "My most generous interpretation... all humans need the same things whether one or forty-five.",
    "leadership",
    "Assume unmet needs drive ineffective behavior before malice.",
    "MG I on confusing actions; translate to needs/skills; respond with curiosity.",
    "PM facing sabotaging stakeholder",
    ["They're political on purpose", "Generosity is naivete"],
    ["Reorgs", "Resource fights"],
    ["Immediate escalation", "Character assassination"],
    ["Questions shift from blame to needs"],
    ["Reduced vendetta energy"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["MG I as team norm", "Pair with boundaries when pattern persists"],
    ["Don't attribute to AI malice what is context error—parallel for agents"])

# --- MARC ANDREESSEN ---
ep, g = "Marc Andreessen: The real AI boom hasn't even started yet", "Marc Andreessen"

add(ep, g, "Task Loss Not Job Loss Frame",
    "Everybody wants to talk about job loss, but really look at task loss. The job persists longer than individual tasks.",
    "strategy",
    "Work redesign unit is tasks within jobs not job titles.",
    "Map task bundles for PM/eng/design; swap tasks via AI; expect titles to lag task reality.",
    "Leader planning workforce strategy",
    ["Jobs disappear overnight", "AI replaces companies in one wave"],
    ["Union/job title politics", "Hiring freezes"],
    ["Frozen roles while tasks shift", "Resume-based hiring mis-fit"],
    ["Executives now do own email"],
    ["Secretary role evolved not vanished"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Task audits per role", "Retrain on new task bundles"],
    ["Orchestrating agents is new task layer on engineering"])

add(ep, g, "PM Eng Design Mexican Standoff",
    "Mexican standoff between PM, designer, coder—each believes AI lets them do the other two jobs.",
    "org_design",
    "All three roles are partially right; combination beats silo.",
    "Encourage cross-skilling with AI; reward triple-threat builders; don't protect stovepipes.",
    "Tech company functional org",
    ["Functions stay pure", "AI only helps your function"],
    ["Territorial leaders", "Tool access gated by role"],
    ["Everyone mediocre at all three", "Quality drops from dabbling"],
    ["Coders shipping designed prototypes", "PMs running agents"],
    ["Designers coding experiments"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Career paths for hybrid builders", "Shared agent tooling"],
    ["Super-empowered individuals outproduce three-person pods"])

add(ep, g, "Super Empowered Individual Curve",
    "Really great people becoming spectacularly great... not twice as good, ten times.",
    "talent",
    "AI widens performance distribution at individual level.",
    "Invest in top talent agency; give leverage tools; expect wider output spread.",
    "Parent/leader developing high-potential ICs",
    ["AI raises everyone equally", "Mean matters more than tails"],
    ["Comp compression fights", "Tool bans"],
    ["Middle disengagement", "Star dependency risk"],
    ["10x coder anecdotes", "Friends reporting step-change"],
    ["Envy management"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Homeschool plus AI tutoring for depth", "Agency cultivation"],
    ["Winners are spectacularly great hybrids; hire for agency plus craft"])

add(ep, g, "Demographics Plus AI Timing",
    "If we didn't have AI we'd panic about depopulation... remaining human workers at a premium.",
    "strategy",
    "Labor scarcity and low productivity growth context reframes AI as necessity.",
    "Plan for human premium skills; don't assume endless labor supply; pair AI with population trends.",
    "Macro-thinking founder/investor",
    ["AI creates mass unemployment now", "Immigration trends unchanged"],
    ["Policy shifts on immigration", "Aging economies"],
    ["Dystopian jobless narrative only"],
    ["Optimistic labor scarcity takes"],
    ["Political fights on immigration"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Invest in human trust skills", "Automate atoms-hard sectors slowly"],
    ["Human relationship work gains relative price"])

add(ep, g, "Productivity Growth Reality Check",
    "Productivity growth last 50 years very low... AI hits economy that had almost no technological progress.",
    "strategy",
    "Felt digital change ≠ measured economic acceleration until now.",
    "Under-price one-dimensional 'AI eats world'; model interaction with demographics and institutions.",
    "Investor framing AI impact",
    ["Tech Twitter equals economy", "Every sector already transformed"],
    ["Healthcare cartels block change", "Regulatory moats"],
    ["Overhype instantaneous ubiquity"],
    ["Bits progress vs atoms stagnation debate"],
    ["Peter Thiel atoms critique acknowledged"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Target sectors with verifiable answers first", "Policy advocacy where blocked"],
    ["Reasoning/medical domains with evals see gains first"])

add(ep, g, "Philosopher Stone Framing",
    "AI transfers sand into thought—the philosopher stone.",
    "strategy",
    "Fundamental commodity shift is intelligence on tap.",
    "Teach kids to leverage AI as lever; spend spare hours training with models.",
    "Homeschooling tech parent",
    ["AI is just chatbot", "Intelligence not commoditizing"],
    ["Kids banned from computers myth", "Educational system inertia"],
    ["Underuse of tutoring leverage"],
    ["10-year-old arguing with AI for fun"],
    ["Parent fear of screen time"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["AI-augmented tutoring hybrid", "Alpha-school style models"],
    ["Bloom 2-sigma via LLM at scale"])

add(ep, g, "Agency Over Rule Following",
    "Huge premium on people able to take responsibility... in order to lead you must learn to obey.",
    "leadership",
    "Agency matters but structure and discipline enable it.",
    "Build initiative in kids/ICs; pair with grounding rules; avoid pure rule-following culture.",
    "Parent or founder cultivating talent",
    ["Agency is disrespect", "School-style compliance optimal"],
    ["Risk-averse institutions", "Founder youth without management exp"],
    ["Rebels without execution", "Obedient without initiative"],
    ["Live player language", "California agency discourse"],
    ["Tension between structure and freedom"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Homeschool for N=1 optimization", "Reward responsible risk-taking"],
    ["AI rewards agency—prompting is initiative"])

add(ep, g, "Calculator Job Evolution Parable",
    "Job of programmer was calculators in rooms... now argue with coding bots.",
    "culture",
    "Each abstraction layer redefines programmer tasks not eliminates humans.",
    "Learn to evaluate agent output; orchestrate parallel bots; depth still matters for debug.",
    "Engineer facing vibe coding",
    ["Programming ends", "No need to understand code"],
    ["Scripting wasn't real programming fight repeats"],
    ["Blind vibe shipping"],
    ["Seniors monitoring ten terminals"],
    ["Identity loss among hand-coders"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Teach kids code reading while agents write", "Career paths as bot orchestrators"],
    ["Historical pattern says humans stay in loop at new abstraction"])

# --- JASON COHEN ---
ep, g = ("5 questions to ask when your product stops growing | "
         "Jason Cohen (2x unicorn founder)"), "Jason Cohen"

add(ep, g, "Churn Ceiling Arithmetic",
    "100 new customers divided by 5% cancellation = 2,000 customer ceiling.",
    "growth",
    "Logo churn creates hard asymptote regardless of marketing hustle.",
    "Compute max customers from new logos / churn rate; fix churn before scaling acquisition.",
    "SaaS founder with slowing growth",
    ["More marketing fixes plateau", "Churn is minor at 5%"],
    ["Investor push for growth", "Leaky bucket denial"],
    ["Scaling ads into ceiling", "Ignoring negative reviews from churners"],
    ["Visceral 'we'll never exceed X customers'"],
    ["Panic spend on ads"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Churn math in board decks", "Prioritize logo churn before channel tests"],
    ["AI can't outmarket exponential churn drag"])

add(ep, g, "What Made You Cancel Question",
    "Changed from 'why did you cancel' to 'what made you cancel'—usable responses doubled.",
    "product",
    "Wording steers churners from excuses to product causality.",
    "Use open-ended 'what made you cancel'; avoid dropdown noise; randomize any lists.",
    "SaaS ops analyzing exit surveys",
    ["Dropdowns give clean data", "AI can replace reading responses"],
    ["Low response rates", "Legal fear of open text"],
    ["First dropdown option bias", "Too expensive as accepted truth"],
    ["Groove case study 10% to 20% usable"],
    ["Teams trust 'budget' label"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Randomized cancel forms", "Human reads details AI summarizes themes only"],
    ["LLMs good at themes bad at actionable anomalies—keep human detail pass"])

add(ep, g, "Too Expensive Is Never The Reason",
    "They already saw pricing and bought... too expensive is never ever the reason.",
    "product",
    "Stated price objection after purchase signals unmet promise not price sensitivity.",
    "Five-whys style root-er causes; probe integrations, onboarding, segment fit.",
    "Founder reading churn reasons",
    ["Believe cancel survey literally", "Cut price first reflex"],
    ["Enterprise budget loss vs price", "Competitor switch masked as cost"],
    ["Price cuts without signup change"],
    ["Surprise when price raise doesn't hurt"],
    ["Patrick Campbell underpricing quote"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Talk to almost-canceled users", "Segment ICP for retention"],
    ["AI pricing optimizers miss promise failure"])

add(ep, g, "Pricing Selects The Market",
    "Pricing selects the market... $2/month looks low quality to 400M revenue company.",
    "pricing",
    "Price is segmentation signal not just demand lever.",
    "Raise prices to attract serious buyers; expect signups unchanged or up; repeat until elastic.",
    "Bootstrapped/devtool underpricing",
    ["Demand curve always slopes down", "Cheap equals PLG advantage"],
    ["Fear of raising prices", "Competitor anchor only"],
    ["12x price test no signup change story"],
    ["Enterprise ignores tool"],
    ["Founder emotional attachment to accessible price"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Iterative price raises with measured signup rate", "Value-based packaging"],
    ["AI features justify premium positioning"])

add(ep, g, "Ordered Growth Diagnostic Gauntlet",
    "Series of questions in order—first problem if you don't fix it, rest doesn't matter.",
    "growth",
    "Growth stalls have priority order: logo churn, pricing, NRR, channels, need-to-grow.",
    "Run five-question diagnostic sequentially; don't tune bottom of funnel if top question fails.",
    "Founder with decelerating SaaS",
    ["All growth tactics parallel", "Random experiments"],
    ["Economy blame only", "AI threat narrative only"],
    ["Fixing ads while churn 7%", "NRR work before churn fixed"],
    ["Feeling mud running"],
    ["Will Smith fame quote resonance"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Checklist discipline", "Stop if question one unhealthy"],
    ["Same framework when AI shifts channels—churn still first"])

add(ep, g, "Onboarding Leverage Point",
    "If you don't know what to do, focus on onboarding... small front-end shift huge revenue impact.",
    "product",
    "Early lifecycle churn dominates; fixes there multiply.",
    "Treat onboarding like YouTube first-30-seconds retention; intervene pre-cancel when signals show trouble.",
    "SaaS with heavy early churn",
    ["Onboarding is solved", "Only feature work matters"],
    ["Low data startups", "High volume support"],
    ["Ignoring pre-cancel signals"],
    ["50% drop first 30s YouTube analogy"],
    ["Success teams only post-cancel"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Playbooks for at-risk behaviors", "Talk to troubled-not-canceled"],
    ["AI can personalize onboarding—still highest ROI lever"])

add(ep, g, "Good Vs Bad Customer Correlation",
    "What good customers have in common that bad customers don't—not what good alone share.",
    "growth",
    "Retention work requires discriminative correlates not generic power-user traits.",
    "Compare successful vs churned cohort behaviors; avoid actions both groups share.",
    "Growth team mining product analytics",
    ["Copy power users only", "More data always needed first"],
    ["Small sample paranoia", "False precision from AI themes"],
    ["Targeting traits everyone has"],
    ["Discriminative feature analysis"],
    ["Misleading correlates"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Cohort contrasts before automation", "Human judgment on weird outliers"],
    ["AI averages hide discriminative churn signals"])

add(ep, g, "Do You Need To Grow Question",
    "Last question: do you need to grow? If you're not growing you're dying—is that true?",
    "strategy",
    "Not every stall requires growth; investor narrative ≠ company health.",
    "Ask if growth is necessary now; consider profitable steady state; resist investor slogans blindly.",
    "Bootstrapped or lifestyle-adjacent SaaS",
    ["Growth always mandatory", "Stall means failure"],
    ["VC pressure", "Founder identity tied to hockey stick"],
    ["Forced growth into bad fit markets"],
    ["Relief when question posed"],
    ["Investor-founder tension"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Explicit choice to stay small", "Fix retention without scale ambition"],
    ["One-person profitable businesses viable in AI era"])

# --- ZEVI ARNOVITZ ---
ep, g = ("The non-technical PM's guide to building with Cursor | "
         "Zevi Arnovitz (Meta)"), "Zevi Arnovitz"

add(ep, g, "Virtual CTO Project",
    "Created a CTO with custom prompt... I own the problem, you're complete owner of how it's built.",
    "execution",
    "Non-technical builders need adversarial technical owner persona before coding agents.",
    "GPT/Claude project as CTO: challenge ideas, forbid people-pleasing, separate problem from implementation.",
    "Non-technical PM at Meta building side products",
    ["Jump straight to Cursor", "ChatGPT default sycophancy enough"],
    ["Architecture mistakes", "People-pleaser AI agrees with bad ideas"],
    ["Bun vs Zustand riffing incident"],
    ["CTO project challenges dumb ideas"],
    ["Fear of code view"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Graduate Lovable → Cursor slowly", "Exposure therapy to code"],
    ["Plan mode in tools replicates part of CTO role"])

add(ep, g, "Plan Before Code Agent Discipline",
    "Coding agents eager to write code... planning is really important for payments/database changes.",
    "execution",
    "Premature coding agents cause gnarly bugs; enforce planning phase.",
    "Use ask/plan modes; block build until spec; especially for schema/payment work.",
    "Vibe coder on Bolt/Lovable/Cursor",
    ["Speed means immediate code", "Plans are bureaucracy"],
    ["Payment integration fires", "DB corruption scares"],
    ["Agent starts coding on vague prompt"],
    ["80% chat 20% execute ratio like Lazar"],
    ["Regret after merge"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Linear integration for ideas", "Slash commands for review"],
    ["Native plan modes in tools encode lesson"])

add(ep, g, "Multi Model Code Review",
    "/review plus Codex and Cursor each review the code.",
    "execution",
    "Non-technical builders compensate via redundant model review.",
    "After agent writes code, orchestrate cross-tool reviews; don't trust single model.",
    "PM shipping without code literacy",
    ["Can't review code so ship blind", "One model enough"],
    ["Missed security issues", "Over-confidence"],
    ["Triple review before merge"],
    ["Engineers ask Zevi to teach them"],
    ["Imposter syndrome"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Publish prompts/commands", "Meta engineers learning workflow"],
    ["Review bottleneck shifts to orchestration"])

add(ep, g, "Gradual Dark Mode Exposure Path",
    "Start GPT project beautiful UI... graduate Bolt/Lovable... Cursor light... terminal dark mode.",
    "career",
    "Confidence ramp reduces terror of code surfaces.",
    "Staged exposure: chat-only → no-code builders → IDE light → terminal; learn from agent text not syntax.",
    "Music-background PM learning to build",
    ["Start in terminal day one", "Must learn CS first"],
    ["Overwhelm quit", "Skips planning discipline"],
    ["Panic at stack traces"],
    ["Light mode Cursor comfort"],
    ["Pride in dark mode later"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Documented ramp in show notes", "Tal Raviv referral network"],
    ["Every PM can copy ramp; Meta internal demand signal"])

add(ep, g, "Titles Collapse Prediction",
    "In coming years everyone's going to become a builder; titles and responsibilities collapse.",
    "org_design",
    "Function lines blur when PMs ship real products solo.",
    "Invest in building literacy; engineers teach PM workflows; reward shipped artifacts.",
    "Meta PM with engineers asking to learn",
    ["PMs stay spec-only", "Engineers gate production"],
    ["Security blocks non-technical ship", "Review burden"],
    ["PMs shipping internal tools", "Engineers requesting Zevi training"],
    ["Career ladder confusion"],
    ["Competing function identities"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Share prompts org-wide", "Success = readers open laptop and build"],
    ["Hybrid PM-builder role formalizes"])

add(ep, g, "Best Time To Be Junior",
    "Best time to be a junior... get out of school and build a startup on your own.",
    "career",
    "Entry-level scarcity offset by unprecedented solo build leverage.",
    "Juniors should ship side projects with agents; employers value demonstrated builders.",
    "New grad PM/engineer",
    ["Junior roles gone so give up", "Need big co apprenticeship first"],
    ["No mentors", "Credentialism"],
    ["Solo startups from dorm", "Public builds"],
    ["Senior gatekeeping"],
    ["Portfolio over pedigree"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["AI replaces juniors myth countered"],
    ["Agency plus AI beats waiting for headcount"])

add(ep, g, "Success Metric Is Others Building",
    "If people walk away thinking how amazing you are, you failed... if they open computer and build, succeeded.",
    "culture",
    "Teaching metric is replication not admiration.",
    "Optimize episodes/docs for copy-paste prompts; engineers should start same day.",
    "Guest on podcast/demo",
    ["Inspire-only content", "Gatekeep advanced tips"],
    ["Viewer awe zero action", "Complexity performance"],
    ["Downloads of commands", "Show notes prompts"],
    ["Claude prepped humility"],
    ["Ego from praise"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Open-source slash commands", "Linear→plan→build demo"],
    ["Content that doesn't enable build is entertainment"])

add(ep, g, "Memory Vs Projects Compartmentalization",
    "Memory feature mixed running with product reviews... projects compartmentalize context.",
    "execution",
    "Separate contexts prevent cross-domain contamination in AI work.",
    "Use projects per domain (PM vs hobbies); avoid global memory for multi-hat roles.",
    "PM who is also runner/psychology student",
    ["One chat for everything", "Global memory always helps"],
    ["Bad advice from mixed context", "Wrong tone in prompts"],
    ["5K conflated with product review"],
    ["Clean project boundaries"],
    ["Annoyance at memory bleed"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Project per product/initiative", "Custom instructions per workspace"],
    ["Agent memory policies become enterprise requirement"])

# --- SAM LESSIN ---
ep, g = ("How to show up in any room with a low heart rate: Silicon Valley's missing etiquette playbook | Sam Lessin"), "Sam Lessin"

add(ep, g, "Low Heart Rate Room Entry",
    "Etiquette is a skill for how to show up in a room with a low heart rate.",
    "leadership",
    "Calm presence beats transactional intensity in high-stakes rooms.",
    "Prepare buffer time; abundance mindset; build relationships not card collection.",
    "First-time founder at KP holiday party",
    ["Hustle means high intensity", "This is your one shot"],
    ["Room full of VCs", "Immigrant/first-gen anxiety"],
    ["Energizer bunny networking", "Over-apologizing lateness drama"],
    ["Repeating names back", "Firm handshake without crush"],
    ["Scarcity panic"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Be early not 30 min early", "Simple apology if late"],
    ["AI won't replace trust-building at dinners"])

add(ep, g, "Etiquette As Trust Infrastructure",
    "When technology is a major deal, etiquette matters for partnerships and data trust.",
    "sales",
    "Soft skills compound when tech commoditizes.",
    "Mirror expected behaviors; hygiene basics; seriousness about enterprise trust.",
    "Founder selling to Fortune 500",
    ["Product alone closes", "Being abrasive signals authenticity"],
    ["Enterprise procurement", "Job loss fear meetings"],
    ["Odor/background fails", "Over-familiarity on first meet"],
    ["Delphi clone in meetings vision"],
    ["Fear of being fake"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Teach classes internally", "Book as memorable hook"],
    ["Buyer-side agents still evaluate human trust signals"])

add(ep, g, "Abundance Over Scarcity Networking",
    "Show up with self-confidence and calm of abundance... this isn't your one shot.",
    "career",
    "Relationship building is long game not single conference conversion.",
    "Give more than take; avoid collecting cards; repeat names with eye contact.",
    "Young founder networking events",
    ["Must close every conversation", "Follow-up spam"],
    ["High-stakes room", "Comparison to legends"],
    ["Transactional pitches instantly"],
    ["Calm curiosity questions"],
    ["Relief when not pressured"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Peer etiquette classes", "Practice low-heart-rate intros"],
    ["Avatars attend meetings—but human trust still gates big deals"])

add(ep, g, "Be Early Buffer Discipline",
    "Be early... buffer so heart rate isn't up when you enter.",
    "execution",
    "Arrival state shapes entire interaction quality.",
    "Target a few minutes early; brief wait to compose; simple apology if late—no drama.",
    "Operator chronically late",
    ["Lateness shows importance", "Detailed excuses help"],
    ["Back-to-back Zooms", "Travel chaos"],
    ["Flustered entrances", "Dominating with apology monologue"],
    ["Composed entry"],
    ["Shame spiral on tardiness"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Calendar buffers", "Waiting room minute to breathe"],
    ["AI schedules tight—but human first impressions still physical"])

add(ep, g, "Don't Make Late People Feel Bad",
    "If somebody else is late, do not make them feel bad—opposite of your own late behavior.",
    "leadership",
    "Grace for others' lateness reduces room tension.",
    "When guest arrives late: welcome simply, move on; no performative punishment.",
    "Host of founder dinner",
    ["Punctuality moralism", "Power move on latecomers"],
    ["VIP late arrival", "Team watching leader reaction"],
    ["Public callouts", "Passive aggression"],
    ["Guest relaxes and contributes"],
    ["Status games at door"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Model grace publicly", "Private feedback if chronic"],
    ["Human rapport still local even when agents schedule"])

add(ep, g, "Hilarious Plus Useful Cutthrough",
    "Things at intersection of hilarious and useful... humor cuts noise but needs deeper truth.",
    "marketing",
    "Memorable teaching requires comedy plus operational payoff.",
    "Package etiquette as funny-but-true; double down on viral hooks that teach behaviors.",
    "VC teaching founders soft skills",
    ["Pure humor fluff", "Dry etiquette pedantry"],
    ["Feed saturation", "Cynical audience"],
    ["Tweet → event → book ladder"],
    ["Eye rolls vs shares"],
    ["Authenticity debates"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Limited edition book urgency", "Classes worldwide"],
    ["Founders share etiquette memes—distribution via humor"])

add(ep, g, "Ship Early Etiquette Canon",
    "Ship early ship often... V1 good limited edition, evolves with crowd feedback.",
    "product",
    "Iterative public teaching product like software.",
    "Launch incomplete playbook; collect gaps; expand categories from users.",
    "Creator building etiquette curriculum",
    ["Wait until comprehensive", "Perfect before launch"],
    ["Missing cultural contexts", "Global audience"],
    ["Stale rules"],
    ["Community suggests new chapters"],
    ["Perfectionism paralysis"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Versioned editions", "Feedback-driven expansions"],
    ["Same loop for AI product docs and social norms content"])

add(ep, g, "Founder Abrasion Myth Reversal",
    "Silicon Valley encouraged abrasive on purpose... etiquette shows trustworthy counterpart.",
    "culture",
    "Intentional abrasiveness was over-rotated; trust wins partnerships.",
    "Keep product edge; soften interpersonal friction; especially with data-sensitive buyers.",
    "Holed-up engineers entering enterprise sales",
    ["rudeness signals genius", "Investors reward jerk geniuses only"],
    ["Enterprise trust requirements", "Team cross-functional friction"],
    ["Lost deals from vibe", "HR complaints"],
    ["T-shirt exec teaching manners"],
    ["Defensive 'authenticity'"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Etiquette classes for portfolio", "Pair technical demos with conduct norms"],
    ["As code commoditizes, manners differentiate"])

# --- ALEXANDER EMBIRICOS ---
ep, g = ("The power user's guide to Codex: parallelizing workflows, planning techniques, advanced context engineering tips, automating code reviews, and more | Alexander Embiricos"), "Alexander Embiricos"

add(ep, g, "OpenAI Bottoms Up Empiricism",
    "Org set up to try things quickly... aiming fuzzily a year out, empirical on product that lands.",
    "org_design",
    "When capabilities uncertain, run many fast experiments not annual roadmaps.",
    "Fuzzy long-range aim; weekly/monthly empirical bets; humble learning loops.",
    "AI product org post-Dropbox startup founder",
    ["Everyone can copy OpenAI process", "Bottoms up without talent works"],
    ["Middle timeline planning paralysis", "Top-down roadmaps"],
    ["Over-planning 6-9 month bets"],
    ["Reddit praise/complaint monitoring"],
    ["PMs rally ship traditionally"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Ready-fire-aim culture", "Talent-caliber-adjusted process"],
    ["Few companies can run true bottoms-up at AI speed"])

add(ep, g, "Codex As Teammate Not IDE",
    "Codex is beginning of software engineering teammate... smart intern that won't read Slack unless asked.",
    "product",
    "Agent must expand across SDLC not just autocomplete.",
    "Pair today; push toward proactive teammate across plan/validate/maintain; inject Datadog/Slack context.",
    "Codex product lead",
    ["IDE features are end state", "Autonomy day one"],
    ["Trust without observability hooks"],
    ["Users prompt-then-forget"],
    ["Sora Android 18+10 day ship story"],
    ["Engineers still review everything"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Proactivity roadmap", "Context connectors"],
    ["Winning agents = coding agents with computer use"])

add(ep, g, "Human Typing Speed Bottleneck",
    "Limiting factor is human typing speed or human multitasking speed.",
    "strategy",
    "AGI adoption gated by human orchestration bandwidth before model IQ.",
    "Design for parallel agents; reduce review friction; async workflows.",
    "Platform thinking about AGI timelines",
    ["Models alone unlock AGI UX", "Unlimited parallel human attention"],
    ["Review queue explosions", "Too many agent threads"],
    ["Karpathy gnarly bugs hour-long runs"],
    ["Power users maxed out"],
    ["Anxiety about keeping up"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Parallel Codex workflows", "Better review UX"],
    ["Next breakthrough is human-agent bandwidth interfaces"])

add(ep, g, "Review Code Not Just Write",
    "Major goals: make easier to review code, not just write code.",
    "product",
    "Post-agent era bottleneck is human verification throughput.",
    "Invest in review acceleration; proactive teammate reduces raw PR count confusion.",
    "Fast-scaling Codex adoption org",
    ["More PRs equals success", "Review is old problem solved"],
    ["Humans 100% attention per PR"],
    ["Review fatigue"],
    ["Codex caught config mistakes"],
    ["Self-review circularity fears"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Multi-model review variants", "UI for skim-trust-merge"],
    ["Products that don't solve review fail at agent scale"])

add(ep, g, "Any Agent Should Be Coding Agent",
    "If you want to build any agent, maybe you should be building a coding agent.",
    "strategy",
    "Computer use via code is universal interface for action.",
    "Route agent capabilities through code generation and execution; leverage terminal/composer patterns.",
    "Platform strategist choosing agent architecture",
    ["Chat-only agents sufficient", "No-code flows enough"],
    ["Security fears of code execution"],
    ["Tool sprawl without code"],
    ["Codex on own training infra"],
    ["Sorcerer's apprentice automation"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Code as lingua franca for agents"],
    ["Non-coding agents hit walls; coding agents eat scaffolding"])

add(ep, g, "Accelerate Humans Not Confuse Them",
    "Build tool so it feels maximally accelerating rather than unclear what human should do.",
    "product",
    "UX success is clarity of human role when agent acts.",
    "Monitor Reddit complaints; tune product to reduce ambiguity about next human action.",
    "Codex PM listening to users",
    ["More autonomy always better", "Users want magic black box"],
    ["Users stuck staring at agent", "Benchmark chasing only"],
    ["Complaints about opacity"],
    ["Eval obsession without feel"],
    ["Frustration vs delight posts"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Evals plus qualitative Reddit loop", "Onboarding that states human checkpoints"],
    ["Agents that obscure human role get abandoned"])

add(ep, g, "Sora Speed Case Study",
    "Sora Android fully new app 18 days, public 28 days total.",
    "execution",
    "Extreme compression of ship timeline with Codex leverage.",
    "Study internal workflows enabling 18-day greenfield; replicate patterns not just tools.",
    "Mobile team shipping consumer app",
    ["Mobile needs 6-month roadmap", "Quality requires time"],
    ["Store policy delays", "Team coordination overhead"],
    ["Assuming hype not reproducible"],
    ["Public #1 app store", "Internal Codex dogfood"],
    ["Skeptics outside OpenAI"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Document playbook from Sora team", "Parallel agent orchestration"],
    ["Timeline expectations reset industry-wide"])

add(ep, g, "Proactivity As AGI Delivery Path",
    "Large part of goal is proactive teammate helpful by default—not tens of prompts a day but thousands of benefits.",
    "product",
    "Shift from invoked AI to ambient helpfulness requires proactive agents.",
    "Design Codex to initiate useful work with permissions; expand beyond prompt-driven usage.",
    "OpenAI mission-aligned product team",
    ["Users want full control only", "Proactivity equals spam"],
    ["Privacy backlash", "Wrong autonomous actions"],
    ["Missed help moments", "Prompt-only habit"],
    ["Intern metaphor", "Trust ladder"],
    ["Fear of autonomous changes"],
    ["Stakeholder anxiety and identity threat during transition"],
    ["Graduated delegation like hiring intern", "Slack/Datadog integrations"],
    ["Delivering AGI benefits requires proactive coding agents with guardrails"])

out_path = "operational-intelligence-batch2.json"
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(patterns, f, indent=2, ensure_ascii=False)
    f.write("\n")

counts = Counter(p["source_guest"] for p in patterns)
print(len(patterns), "objects")
for guest, n in sorted(counts.items()):
    print(f"  {guest}: {n}")
