"""Remaining batch5 episodes — imported by generate_batch5.py."""


def register(add):
    # BRENDAN FOODY
    ep = "Why experts writing AI evals is creating the fastest-growing companies in history | Brendan Foody"
    g = "Brendan Foody"
    add(ep, g, "Evals Are the PRD", "If the model is the product, the eval is the product requirement document—and sales collateral.", "strategy", "Capability measurement precedes capability delivery in the RL era.", "Labs run dozens of experiments against eval sets; enterprises map value chain → test harness before automating.", "Expert marketplace feeding frontier labs", "Academic benchmarks substitute for domain evals", "Competitor saturates SWE-bench; board asks for agent V1", "Building agents without success criteria", "Evals also marketing while calling them PRD", "Mercor pitch to every Magnificent 7", "Sales teams want benchmark slides not rubrics", "Map each workflow to professor-style rubric + verifier", "Every company becomes eval author for its workflows")
    add(ep, g, "Pull Not Push Product-Market Fit", "Find customers surprisingly easy to sell where pain is enormous—don't force PMF through persistence alone.", "strategy", "Forced PMF burns capital; pull indicates real bottleneck spend.", "Stay stubborn on thesis, flexible on form; xAI meeting + crowdsourcer flood signaled pivot to direct lab supply.", "19-yo founders bootstrapped to $1M then hypergrowth", "Conviction excuses ignoring market", "Seed stage with wrong wedge", "Selling marginal customers into huge business", "Donut Dynasty 'you can just do things' vs forced enterprise sales", "Chasing every inbound middleman", "Investors doubting young founders", "Say no until one flagship lab win; then scale", "Eval demand pull persists while pre-training commoditizes")
    add(ep, g, "Leading Indicators Over Why-Now Story", "Optimize for market leading indicators—wealthiest buyers paying anything to move model capability—not legacy automation TAM slides.", "strategy", "In fast markets, indicator tracking beats narrative decks.", "Watch lab spend shifts (generalist→expert data); orient product to flagship customer bottleneck; ignore stagnant incumbent TAM.", "AI infra startup at least paradigm shift", "Product why-now sufficient alone", "Competitor fundraising FOMO", "Building resume-matching when labs need rubrics", "Bootstrapped profitable while chasing hypergrowth", "Benchmark promised 50M run rate skeptics then hit", "VCs calling insane projections", "Weekly revenue/capability indicator reviews", "Indicator chases move quarterly—eval demand replaces label demand")
    add(ep, g, "Customer Obsession Without Sales (Year 1.5)", "Zero sales/marketing headcount—100% resources on product/experience; word-of-mouth from flagship labs.", "go_to_market", "In supply-constrained hypergrowth, product IS distribution to labs.", "CEO time on customers + hiring; defer marketing sophistication until love creates pull; immature GTM accepted.", "Young hypergrowth AI company", "Sales never needed", "Enterprise procurement cycles", "Under-investing in brand until competitors narrate market", "Now adding PMs to GTM while proud of no-sales era", "Labs asking for 24h expert turnaround", "Founders feeling behind on marketing", "Sundeep Jain/Uber scale hire when pull proven", "Labs evaluate vendors via eval quality samples—not decks")
    add(ep, g, "Can-Do × High Standards × Intensity", "Three values: ridiculous goals that trajectory forms around; elite hiring bar; output-oriented intensity (not mandated 996).", "culture", "Hypergrowth requires ambition + talent density + ownership—not performative hours policy.", "Set absurd public targets (1.5M→50M run rate); hire ex-founders/Scale leaders early; intensity by opt-in ownership.", "Fastest revenue ramp startup", "996 mandatory for everyone", "Talent market emphasizing wellbeing", "Burnout attrition; goals without execution", "Clarifies not mandating 9-9-6 while describing late nights                  nights", "Benchmark doubters then beating by 2 weeks", "Pride in capital efficiency", "First 10 patient; 10→100 speed once vacuum proven", "AI talent war makes values table stakes not differentiator")
    add(ep, g, "Elastic Demand Career Bets", "Invest in domains where 10× productivity increases demand (software, PM)—not inelastic (accounting).", "career", "AI expands output in elastic categories more than it eliminates headcount there.", "Assess elasticity of field; hire/interview with 'use any AI tool build in an hour' tests; calculator analogy for AI-native.", "Students and PMs planning careers", "All knowledge work equally elastic", "Parents pushing safe accounting paths", "Under-indexing AI fluency", "Andreessen software elasticity tweet alignment", "Enterprises fearful of eval-ing their value chain", "FOMO vs displacement narrative", "Assess with AI-open-book interviews", "Eval author + AI-native operator = new high-paid category")
    add(ep, g, "Economy as RL Environment", "Entire economy may become rubric/verifier generation for models—new job category not just displacement.", "strategy", "Human work shifts to defining success in domains models can't yet pass.", "Track expert rubric writing as durable work; prepare upskilling for verifier roles; abundance framing over UBI-only.", "Expert labor marketplace CEO", "Superintelligence in 3 years zeroes need", "Policy panic on job loss", "Ignoring displacement friction", "Retweets 'put on Earth for RL data' provocatively but argues new jobs", "Media displacement-only narrative", "Optimism on medical/legal access", "Industrial revolution analogy in messaging", "Long-horizon eval demand even as models automate tasks")
    add(ep, g, "Initiative Barrier to Innovation", "Biggest barrier to more innovation is initiative—build and talk to customers now that building is easier.", "founder_mindset", "Distribution of execution attempts matters more than idea quality in AI glut.", "Stop podcast-only learning; ship weekend projects; Mercor born from teenage donut arbitrage mindset.", "Young AI founders", "Ideas are scarce", "School/credential paths", "Consumption without building", "Dyslexic CEO leverages strengths not reading inbox", "Users listening not building", "Shame about non-traditional path", "Public 'you can do things' mandate", "AI lowers build cost—increases return to initiative and customer contact")
    add(ep, g, "Post-Training Bottleneck Thesis", "Labs' binding constraint is measuring success across domains—not more pre-training corpus.", "strategy", "Improvement curve follows verifiers and expert rubrics, not raw tokens.", "Invest in expert-sourced eval/RL data; expect decade+ human-in-loop; synthetic helps verifiable domains only.", "Human data supply chain", "Pre-training scaling solves all", "Model plateau narrative", "Overbuilt generalist label ops", "Disagrees with 3-year superintelligence while bullish automation", "MBAs declaring data labeling dead", "Expert pride in domain work", "Quality×volume×speed trifecta for lab buyers", "Post-training spend rivals pre-training—enterprise fine-tune loops follow")

    # ETHAN SMITH
    ep = "The ultimate guide to AEO: How to get ChatGPT to recommend your product | Ethan Smith"
    g = "Ethan Smith"
    add(ep, g, "Citation Frequency Beats Rank One", "In LLM answers, being mentioned most across citations beats holding citation #1—summarization not SERP.", "growth", "Head queries reward share-of-voice in synthesis, not blue-link position.", "For 'best X' queries: optimize multi-source mentions (YouTube, Reddit, affiliates)—not single-domain rank alone.", "B2B growth team adding AEO lane", "Traditional SEO playbook fully transfers", "Incumbent domain authority advantage", "Optimizing only owned landing page rank", "SEO fundamentals still work for AEO tail", "Webflow wins with SEO + YouTube + Reddit combo", "SEO purists dismiss AEO", "Track mention frequency not rank alone", "RAG makes citation graph primary battlefield")
    add(ep, g, "Early-Stage AEO Before SEO", "Startups can't win SEO early (domain authority)—can win AEO tomorrow via citations and long-tail questions.", "growth", "Answer engines lower barrier for new brands on head and tail.", "Pre-Series B: skip heavy SEO; invest citation optimization + hyper-specific question pages; YC launch → answer inclusion.", "Early B2B SaaS", "SEO always later-stage channel", "Investor pressure for Google pipeline", "Spreading thin on mid-funnel SEO", "Contradicts classic 'don't do SEO early' with AEO exception", "Founders ignoring ChatGPT referral line", "SEO agency scope creep", "Question research from sales/support calls", "AI search grows—early citation wins compound in RAG")
    add(ep, g, "RAG Optimization Not Training", "Controllable AEO is mostly retrieval-augmented generation layer—not core model training (slow, obscure).", "growth", "Marketing levers sit in live search/citation path, not Common Crawl poisoning.", "Focus offsite/onsite for RAG citations; block training bots optionally; expect year-lag for core model influence.", "Graphite research-led growth org", "Getting into training data is practical strategy", "Brand spam pages for model memorization", "Wasted effort on million-page AI slop", "Studied AI content correlation—10-12% detected, doesn't win", "Clients asking to poison Common Crawl", "Research team vs execution team split", "Citation strategy by surface (Perplexity 70% Google overlap vs ChatGPT 35%)", "More surfaces = more RAG graphs to optimize")
    add(ep, g, "Authentic Reddit Not Astroturf", "Real employees: identify self, workplace, give useful answer on relevant threads—five good comments beat 100 fake accounts.", "growth", "LLM trust in Reddit depends on community moderation, not growth-hack spam.", "Find citation threads; post authentic expertise; avoid fake account farms (banned, deleted).", "Growth lead under AEO pressure", "Obvious spam scales", "Competitive AEO wars", "Brand damage; Reddit bans; LLM de-indexing bad UGC", "ChatGPT tunes for Reddit trust intentionally", "Hundreds of fake accounts deployed", "Community backlash", "Deel pre-AI playbook as model", "Reddit remains anti-spam gate for answer quality")
    add(ep, g, "6× LLM Conversion vs Google", "Webflow: LLM referral traffic converts ~6× Google search—conversation builds intent before click.", "The metrics", "Answer-engine leads are higher-qualified, not just new volume.", "Measure beyond last-touch: track answer inclusion + post-conversion 'how heard'; expect branded/direct inflation from LLM influence.", "B2B SaaS marketing analytics", "LLM traffic equals Google quality", "CFO dismisses small referral %", "Ignoring LLM because analytics undercount", "8% signup share from LLMs at Webflow—large channel", "Attribution team skeptical", "Sales loves 'hot' LLM-sourced leads", "Control-group AEO experiments", "Agent recommendations may bypass click—attribution harder")
    add(ep, g, "Control Group AEO Experiments", "200 questions: 100 intervention, 100 control—reproduce before believing AEO best practices.", "experimentation", "Most SEO/AEO advice never tested—reproducibility required.", "Baseline tracker; intervene on Reddit/YouTube/affiliates per bucket; compare share-of-voice vs control; repeat.", "Research-driven SEO consultancy", "Cheap tracker equals premium", "Client wants quick wins without method", "False causality from market drift", "Calls most blog advice wrong while publishing research", "Clients buying $50k commodity trackers", "Academic rigor pride", "Publish replication studies; /5% blog only actionable", "LLM answer variance demands multi-run tracking")
    add(ep, g, "Google Slice Stable, Pie Grows", "Google traffic to publishers not dying—new surfaces (TikTok, AI) add channels; misinformation says Google shrinking.", "strategy", "Zero-sum panic causes wrong budget cuts.", "Maintain SEO; add AEO; treat TikTok/AI as additive; verify with VP Search public data before narrative shifts.", "Marketing leader scared by headlines", "Google obsolete imminently", "Board panic on AI Overviews", "Abandon SEO prematurely", "Every 2 years 'Google dying' cycle", "Agency fear-selling AEO", "Graphite sells both SEO and AEO", "January inflection: clickability + adoption", "Multi-surface optimization becomes default like multi-social")
    add(ep, g, "Information Gain Content Heuristic", "Good content: adds info others lack; not 'typical' rewrite of top 10 Google results—aligns with future algo fixes.", "content", "Typicality detectors will punish copycat SEO content in search and answers.", "Original research, expert credentials, novel data; avoid content-scoring-tool sameness; 5% pages drive 85% traffic—invest there.", "Content org under AI generation pressure", "AI-assisted edited content bad", "Volume SEO mandate from CMO", "Google/ChatGPT as search engine for AI slop", "AI-generated 100% fails study; assisted OK", "Content farms scaling AI pages", "Editors fear AI replacement", "Help center tail for long conversational questions", "AI content flood increases premium on info gain")
    add(ep, g, "Help Center as AEO Surface", "Optimize help center: subdirectory not subdomain, cross-link, fill tail from sales/support questions—win obscure citations.", "product_led_growth", "Follow-up questions in chat map to support docs, not marketing pages.", "Move help to subdir; interlink articles; mine sales calls for tail Qs; community Q expands citation-only topics.", "Support + growth collaboration", "Zendesk defaults sufficient", "Enterprise security blocks community help", "Missing only citation for niche integration queries", "Otter→Looker via Zapier example", "SEO team ignoring help center", "Support resenting marketing intrusion", "Open community questions on long tail", "Agents auto-resolve from help corpus—structure matters more")
