#!/usr/bin/env python3
"""Generate operational-intelligence-batch2.json from batch-2 podcast transcripts."""
import json

P = []

def a(ep, guest, **kw):
    P.append({
        "pattern_name": kw["name"],
        "source_episode": ep,
        "source_guest": guest,
        "source_quote_or_context": kw["quote"],
        "category": kw["cat"],
        "core_belief": kw["belief"],
        "operational_pattern": kw["op"],
        "organizational_archetype": kw["arch"],
        "hidden_assumptions": kw["h"],
        "pressure_scenarios": kw["pres"],
        "failure_modes": kw["fail"],
        "contradictions": kw["con"],
        "behavioral_signals": kw["sig"],
        "emotional_political_dynamics": kw["emo"],
        "operational_adaptations": kw["adapt"],
        "ai_era_implications": kw["ai"],
    })

# BORIS CHERNY
ep, g = "Boris Cherny — Claude Code (Lenny's Podcast)", "Boris Cherny"
a(ep, g, name="Under-resource to force agentic substitution", quote="You want to under-resource things a little at the start… sometimes we just put one engineer on a project.", cat="Team design", belief="Constraint converts headcount pressure into automation faster than training programs.", op="Staff critical paths with one strong engineer plus generous model access; pair with same-day ship norms.", arch="AI-native product lab (Claude Code)", h=["Engineer is motivated to ship", "Token budget not politically capped", "Review gates still exist"], pres=["Crowded coding-tool market", "Pressure to add headcount on fuzzy bets"], fail=["Under-staffing without tokens causes burnout", "Weak engineers hide behind unsafe agent output"], con=["Also subsidizes unlimited tokens at experiment start"], sig=["PR volume per engineer spikes", "Meetings shift from who implements to what agent produced"], emo=["Managers fear looking understaffed", "IC hero velocity until review debt hits"], adapt=["Cap team size on new initiatives; fund tokens liberally"], ai=["Headcount planning becomes orchestrators per N parallel agents"])
a(ep, g, name="Sub-minute feedback as growth engine", quote="Any time someone sends feedback, I fix every single thing as fast as I possibly could—within a minute.", cat="Product operations", belief="Feedback velocity trains the market to keep feeding signal.", op="Treat Slack feedback as real-time queue: acknowledge, fix or agent-fix, close loop publicly.", arch="Developer tools with visible product owner who still codes", h=["Team sustains interrupt-driven work", "Fixes small enough for agents"], pres=["Post-launch spike", "Competitor feature parity"], fail=["Reactive thrashing on loud minorities", "Burnout on sole responder"], con=["Ships early when uncertain—speed for learning not only tickets"], sig=["Rising feedback volume after initial fixes"], emo=["Users feel co-ownership", "PMs sidelined if roadmap is feedback-only"], adapt=["Tier P0 interrupt vs batch", "Automate triage with agents"], ai=["Agents implement micro-fixes at machine speed; human prioritizes taste"])
a(ep, g, name="Subsidize tokens before optimizing", quote="Don't try to optimize at the beginning. Start by giving engineers as many tokens as possible.", cat="AI economics", belief="Exploration and production have different cost curves; premature optimization kills discoveries.", op="Phase 1 uncapped inference for experiments; Phase 2 optimize model tier after proof.", arch="Labs consuming their own models", h=["Finance tolerates spike costs", "Experiments bounded in scope"], pres=["CFO scrutiny after token line exceeds salary"], fail=["Permanent Opus-on-everything with no attribution", "Agents run without shipping"], con=["Under-fund people while over-fund tokens"], sig=["Unlimited tokens as recruiting perk", "200% PR productivity cited"], emo=["Non-AI teams perceive unfair budget"], adapt=["Tag spend by initiative; require demo before renewal"], ai=["OpEx shifts from payroll to inference; finance needs cost per merged PR"])
a(ep, g, name="Mission gravity beats product excitement", quote="What I really missed about Ant was the mission… building a really cool product is not a substitute for that.", cat="Talent", belief="For mission-driven builders, existential purpose is a retention moat competitors cannot buy.", op="Recruit senior builders with safety/mission narrative and autonomy—not feature glamour.", arch="AI safety lab with consumer shipping arm", h=["Mission legible in daily work", "Compensation baseline competitive"], pres=["Hot competitor offers best IDE role"], fail=["Mission washing without decision rights", "Burnout under safety bureaucracy"], con=["Ships fast publicly while mission-first internally"], sig=["Boomerang hires", "Hallway answers converge on one word: safety"], emo=["Product hype teams feel secondary", "Safety researchers tension with fast shipping"], adapt=["Tie roadmaps to mission milestones"], ai=["Talent splits between mission labs and product shops"])
a(ep, g, name="Builder replaces software engineer title", quote="The title software engineer is going to start to go away… replaced by builder.", cat="Role evolution", belief="When code is generated, identity shifts from typing to orchestrating outcomes.", op="Hire and promote for end-to-end shipping with agents; expect painful title/identity transitions.", arch="Anthropic engineering and adjacent functions", h=["Review and taste remain human", "Not all work is code generation"], pres=["Org redesign pressure", "PM/design encroachment"], fail=["Accountability diffusion", "Rubber-stamping agent output"], con=["Still requires deep model understanding to do good work"], sig=["Non-engineers shipping PRs", "Daily multi-PR cadence normalized"], emo=["Identity crisis for career engineers", "PM fear of irrelevance"], adapt=["Builder job descriptions", "Mandatory review on production paths"], ai=["Titles flatten; political capital follows merge rights"])
a(ep, g, name="Agent as coworker not autocomplete", quote="Claude is looking for feedback, bug reports, telemetry… a little more like a coworker.", cat="Product vision", belief="Next shift is proactive agents sourcing work, not passive completion.", op="Wire agents to issue trackers, telemetry, and user feedback channels; human sets direction and review.", arch="Platform team building agentic coding products", h=["Tooling for safe autonomous action exists", "Users trust agent-initiated changes"], pres=["Model capability jumps", "Security incidents from tool use"], fail=["Agents spam low-value PRs", "Humans disengage from direction"], con=["Coworker framing vs accountability for errors"], sig=["Agents open PRs from telemetry", "Humans stop hand-editing"], emo=["Excitement and fear of replacement"], adapt=["Graduated autonomy levels", "Human approval on high-blast-radius"], ai=["Product management becomes agent workflow design"])
a(ep, g, name="Understand the layer under your layer", quote="To do good work you really have to understand the layer under the layer… with AI, understand the model.", cat="Engineering craft", belief="Surface-level tool use without model literacy produces fragile systems.", op="Require post-training immersion or model eval literacy for product engineers on AI surfaces.", arch="Model-coupled product engineering", h=["Time allocated for learning", "Research accessible to product teams"], pres=["Weekly model releases", "Capability regressions"], fail=["Prompt theater without diagnosis", "Blame model when harness is wrong"], con=["Coding solved narrative vs need for deep understanding"], sig=["Engineers do post-training rotations", "Debug via model not only code"], emo=["Research vs product tempo friction"], adapt=["Month on research before shipping", "Eval pods with research"], ai=["Model release ops becomes core product function"])

# BRIAN HALLIGAN
ep, g = "Sequoia CEO coach: Why it's never been easier to start a company, and never been harder to scale one | Brian Halligan", "Brian Halligan"
a(ep, g, name="Constructive dissatisfaction as CEO OS", quote="Perpetual state of constructive dissatisfaction… always a little dissatisfied with where they are, very focused on the end state.", cat="CEO psychology", belief="Resting on wins is competitive liability; dissatisfaction must channel forward not downward.", op="Coach CEOs against past-quarter celebration; peer tables normalize dissatisfaction.", arch="Hyper-growth venture-backed post-PMF", h=["Dissatisfaction paired with end-state clarity", "Board absorbs pace"], pres=["Flat growth after hype", "AI competitor leap"], fail=["Anxiety contagion", "Never celebrating wins"], con=["Also teaches abundance networking mindset"], sig=["Roadmaps always have next act before current peaks"], emo=["Teams feel never enough", "Investors appreciate urgency"], adapt=["48-hour win rituals", "Separate strategy dissatisfaction from people dissatisfaction"], ai=["Faster cycles shorten celebration half-life"])
a(ep, g, name="Spiky interview consensus over well-rounded mediocrity", quote="Four people were four out of four and four were two out of four… we hired the three out of four with weaknesses.", cat="Executive hiring", belief="Leadership teams need challengers and spikes, not averaged interview performance.", op="Shrink panels; weight dissent; use board-deck working sessions; reject compliment-only candidates.", arch="Scaling company replacing founder intuition with exec layer", h=["Spikes align to stage needs", "Culture absorbs conflict"], pres=["Urgent C-level fill", "Pressure for ex-FAANG brand"], fail=["Spiky jerk breaks exec cohesion", "False spike in interviews"], con=["Warns against big-company hires while hiring spikes"], sig=["Heated staff meetings after spiky hire", "Improved outcomes in spike domain"], emo=["HR prefers balanced scorecards"], adapt=["Stage-specific scorecards", "Rehire-probability references"], ai=["Work samples with agents surface spikes faster"])
a(ep, g, name="Kids table vs adults table CEO topology", quote="Under 100 employees… adults over 100… adults spend half their time recruiting and org design.", cat="CEO peer learning", belief="CEO problems are stage-specific; mixing stages produces bad advice.", op="Separate cohorts by company size; kids: PMF/fundraising; adults: exec rebuild and layering.", arch="VC-backed CEO coaching (Sequoia)", h=["CEOs vulnerable in room", "Coach adds framing not dominating"], pres=["CEO at 60 employees facing adult problems without bench"], fail=["Premature scaling playbooks", "Copying adult tactics before revenue durability"], con=["Feedback hardest skill—doesn't transfer across stages automatically"], sig=["Suddenly only talking headhunters and reorgs"], emo=["Shame graduating to adult problems", "Relief in peer normalization"], adapt=["Stage diagnostics before advice"], ai=["Kids table needs parallel AI-native ops track"])
a(ep, g, name="Optionality tax under compressed planning", quote="Massive tax in optionality when you can move this fast… planning cycles now three months.", cat="Strategy", belief="Reversible-choice preservation is expensive when execution bandwidth multiplies.", op="Shorten planning horizons; force one-way doors on quarterly cadence; kill maybe portfolios.", arch="Multi-product platform tempted by AI side quests", h=["Beachhead still has depth", "Team can execute parallel bets"], pres=["Competitor triggers panic diversification", "Board wants ten AI initiatives"], fail=["Thrashing", "Shallow wins everywhere"], con=["Never waste a crisis to over-correct once door opens"], sig=["Many incubators flat core metrics", "Calendar full of alignment not decisions"], emo=["Leaders romanticize optionality as prudence"], adapt=["CEO-owned one-way door list with dates"], ai=["Default planning unit becomes quarterly OKRs plus agent backlog"])
a(ep, g, name="Eat the shit sandwich whole", quote="When you have to eat a shit sandwich, don't nibble… rip the Band-Aid off.", cat="Crisis leadership", belief="Partial corrective actions prolong organizational dread.", op="One clear communication, full scope, single trauma event, then next-play culture.", arch="Public or late-stage private facing macro or quality crises", h=["Leaders withstand short morale hit", "Legal allows single tranche"], pres=["Layoffs", "Outages", "Valuation resets"], fail=["Over-correction ossifies bureaucracy", "Trust damage if misdiagnosed"], con=["Go big on fix not only on cut"], sig=["Repeated small layoff waves", "Rumor mill outruns narrative"], emo=["CEO avoids being hated", "Teams prefer one bad day"], adapt=["Pre-written crisis comms", "War room single DRI"], ai=["Micro-fix temptation on trust events—still need human-visible decisive moves"])
a(ep, g, name="Big-company hire impedance mismatch", quote="50 employees hiring someone from Microsoft 10 years… massive impedance mismatch… 100% attrition on Salesforce/Google/Microsoft hires.", cat="Hiring", belief="Prestige resume brands anti-correlate with startup operating reality at sub-scale.", op="Avoid ex-FAANG exec hires before org maturity; prefer homegrown plus selective free agents (Red Sox model).", arch="50–500 employee scaling startup", h=["Homegrown pipeline exists", "Founder accepts messiness"], pres=["Investor pushes brand-name exec", "Desperate functional gap"], fail=["Culture destruction", "Exec expects processes you don't have"], con=["Red Sox model still uses paid veterans selectively"], sig=["McKinsey cohort phase fails", "Apple/Amazon cohort churn"], emo=["Founder awe at fancy titles", "New hire frustration at chaos"], adapt=["Red Sox mix: farm system plus few veterans", "Blind references with rehire question"], ai=["AI fluency matters more than logo on resume"])
a(ep, g, name="Hire slow fire fast on executives", quote="People hire fast and fire slow… 18 months after C-level hire, at least 50% of the time they're gone.", cat="Executive management", belief="Executive mismatch is common; speed of exit matters more than interview perfection.", op="Extended references and work sessions; plan for 50% exec turnover; shrink interview panels to four.", arch="High-growth startup building exec layer", h=["Board supports fast exec exits", "Blind references honest"], pres=["Functional crisis needing instant fill", "Founder attachment to hire"], fail=["Slow fire poisons org", "Fast hire without references"], con=["Interview improvements help but don't eliminate mortality"], sig=["C-level churn ~2/year at scale", "Parker Conrad board-deck challenge interview"], emo=["Founder guilt on firing", "Exec job-risk on join"], adapt=["Board-deck challenge interviews", "Would you enthusiastically rehire question"], ai=["AI work trials for execs before full commit"])

# SHERWIN WU
ep, g = "Sherwin Wu — OpenAI API / Codex (Lenny's Podcast)", "Sherwin Wu V2"
a(ep, g, name="Surgeon room management for top performers", quote="Spend more than 50% of your time with your top performers… if the surgeon needs a scalpel, the manager already has it ready.", cat="Engineering management", belief="Marginal manager hour on stars beats fixing middling performers when AI leverage is bimodal.", op="Preemptively unblock top ~10% agent-native engineers; let them run 100% agent experiments and broadcast learnings.", arch="Platform/API org at frontier lab scale", h=["Stars share learnings", "Equity story holds for middle tier"], pres=["Bimodal performance reviews", "Reorg threatens experiments"], fail=["Neglect bus factor", "Star hoarding tools"], con=["Larger spans with AI—stars still get disproportionate time"], sig=["70%+ PR gap between cohorts"], emo=["Median engineers feel invisible"], adapt=["Rotation of experiment charter with publish mandate"], ai=["Manager as scalpel-nurse to agent-wielding surgeons"])
a(ep, g, name="Agent failure is usually context failure", quote="When the coding agent is not doing what you want, it's usually a problem with context.", cat="Agent operations", belief="Model is rarely first failure point; missing specs and tribal knowledge are.", op="Forbid roll-up-sleeves escape on experiment teams; add docs, skills, AGENTS.md before swapping models.", arch="100% Codex-written code experiments", h=["Knowledge externalizes faster than model fix", "Escape hatch doesn't hide dysfunction"], pres=["Deadline with stuck agent", "Engineer wants hand-coded hotfix"], fail=["Documentation swamp", "Stale skills files"], con=["Ship despite worst-models-ever meme—context discipline compensates"], sig=["Spike in AGENTS.md commits"], emo=["Seniors blame model", "Manager forces doc work under fire"], adapt=["Blameless postmortems tag context vs capability"], ai=["Repo becomes runtime for org memory"])
a(ep, g, name="Top-down AI mandate without tiger team fails", quote="Exec mandate divorced from what work looks like… find a tiger team of technical-adjacent people who light up.", cat="Enterprise AI adoption", belief="AI adoption is work-specific; mandates without embedded champions produce ROI theater.", op="C-suite buy-in plus dedicated tiger team mapping workflows and internal hackathons.", arch="Non-tech-heavy enterprise forcing AI-first", h=["Champions have carved time", "IT allows tools"], pres=["Board 90-day AI transformation", "Employees feel surveilled"], fail=["Shadow IT", "5% copilot weekly active use"], con=["Silicon Valley assumes literacy rest of world lacks"], sig=["High license spend flat outcomes", "Tiger team Slack only active hub"], emo=["Performance-review trap fear"], adapt=["Fund tiger team full-time", "Measure workflow outcomes not prompts/week"], ai=["AI ops lead per function emerges"])
a(ep, g, name="Models eat scaffolding", quote="The models will eat your scaffolding for breakfast… build for where the models are going.", cat="AI product strategy", belief="Layers existing only because today's model is weak are liabilities with short half-life.", op="Minimize durable bets on vector DBs and heavy frameworks; thin harness plus tools; re-evaluate each model generation.", arch="API/platform on fast model cadence", h=["Team can refactor quickly", "Customers tolerate integration churn"], pres=["Enterprise asks for 2023 RAG architecture", "Investors want AI moat story"], fail=["Under-invest present reliability", "Customer distrust from churning integrations"], con=["Uses Skills today while arguing they may disappear"], sig=["Internal scaffolding half-life tracking"], emo=["Sales wants stable promises", "Eng wants delete code each quarter"], adapt=["Capability-led customer roadmap"], ai=["Moats shift to distribution and data rights not embeddings"])
a(ep, g, name="Production path is the real product bottleneck", quote="The thing that annoys engineers most is after you've written beautiful code, how do you get it into production.", cat="DevOps culture", belief="Agent speed exposes deployment and review as binding constraints.", op="Invest in CI, review UX, and prod access for agents—not only generation.", arch="Platform engineering at OpenAI", h=["Security allows prod automation", "Review culture not rubber-stamp"], pres=["10–30 PRs per engineer per day"], fail=["Merge queue collapse", "Incidents from unreviewed agent PRs"], con=["Generation solved narrative vs ops unsolved"], sig=["Review queue growth", "Engineers complain about deploy not codegen"], emo=["Hype fatigue vs excitement on self-serve tools"], adapt=["Automated review and self-validation", "Risk-tiered review depth"], ai=["Verification experience becomes product moat"])

# LAZAR JOVANOVIC
ep, g = "The rise of the professional vibe coder | Lazar Jovanovic", "Lazar Jovanovic"
a(ep, g, name="Parallel prototype ladder for clarity", quote="Brain dump prompt… second project with more clarity… third with code snippets… upfront costs more, long run saves hundreds of credits.", cat="Vibe coding workflow", belief="Clarity is purchased via parallel disposable builds not polishing one wrong branch.", op="Spin 3–6 shallow projects; pick winner after 1–2 calibration prompts; never tune design on first branch.", arch="Professional vibe coder at hyper-growth startup", h=["Billing rewards batch exploration", "User has taste to pick winner"], pres=["Stakeholder wants tweak on wrong architecture"], fail=["Analysis paralysis", "Security neglected in speed"], con=["Advocates not reading code while using snippets for pixel perfection"], sig=["Six tabs open; winner obvious in minutes"], emo=["Traditional eng scoffs at waste", "Leadership loves demo velocity"], adapt=["Time-box exploration; security gate before prod"], ai=["Agents orchestrate parallel specs; human is tournament judge"])
a(ep, g, name="Externalize context to defeat token amnesia", quote="masterplan.md… tasks.md… Proceed with the next task. I outsource context to the agent.", cat="Context engineering", belief="Long chats fail because agents forget; files and single-task execution beat heroic prompting.", op="After winner: day of planning → tasks.md atomic steps → prompt shrinks to next task; update docs on scope shift.", arch="Non-technical full-time vibe coder shipping prod", h=["Tool respects project knowledge files", "Tasks truly independent"], pres=["70 edge functions—debug without file pointer burns tokens"], fail=["Stale docs lie", "User yells wasting tokens on apologies"], con=["Says don't read code but relies on structured eng artifacts"], sig=["Prompt length collapses", "Checkbox tasks move"], emo=["Anger spiral when obedient model gaslights"], adapt=["Lint doc freshness", "Require file cite before merge"], ai=["PMs own markdown truth in repos"])
a(ep, g, name="Optimize judgment not typing", quote="Coding is not the problem we're solving for… optimizing 100% of my time on good judgment, clarity, quality, taste.", cat="Skill development", belief="When generation is cheap, returns accrue to problem selection and taste.", op="Exposure hours on great products; 80% planning chat; read agent narrative not diffs.", arch="Vibe coder bridging growth GTM product", h=["Org tolerates non-coder owning prod", "Security elsewhere"], pres=["Eng insists on code review standards builder can't pass"], fail=["Beautiful wrong product", "Fast slop"], con=["Structured PRDs without eng training"], sig=["Polished demos high incident rate"], emo=["Career threat to junior devs"], adapt=["Staff eng prod gates", "Taste rubrics in critique"], ai=["Hiring filters shift to critique speed not LeetCode"])
a(ep, g, name="Hire yourself via building in public", quote="It became a job by building in public. You don't need a company to hire you.", cat="Career path", belief="Demonstrated output precedes formal role creation in AI-native companies.", op="Ship public projects; document frameworks; let market pull create professional vibe coder demand.", arch="Individual builder → first official vibe coder hire", h=["Audience and distribution exist", "Quality bar visible publicly"], pres=["Crowded builder space", "Tool vendor hype cycles"], fail=["Performance without substance", "No path to prod maintenance"], con=["Company hire vs solo brand tension"], sig=["Public build logs", "Inbound from growth leaders"], emo=["Imposter syndrome without CS degree"], adapt=["Portfolio of prod-adjacent tools", "Pair with eng for hardening"], ai=["Roles invented faster than job boards update"])
a(ep, g, name="Exploration vibe vs production documentation", quote="Vibe your way for fun while prototyping… when exploration is done, use referencing and agent files.", cat="Workflow phases", belief="Same tool requires different discipline by phase; conflating phases burns tokens and trust.", op="Phase 1: parallel vibes; Phase 2: masterplan and tasks; Phase 3: one task per turn with file pointers.", arch="Professional AI builder", h=["User can tell when exploration ends", "Tests exist for prod phase"], pres=["Demo tomorrow on half-baked branch"], fail=["Prod shipped from exploration branch", "Over-documentation during ideation"], con=["Positive delusion try anything vs planning-heavy process"], sig=["Clear repo doc stack appears after winner picked"], emo=["Frustration at agent apologies"], adapt=["Explicit phase gates in team rituals"], ai=["Agents will self-manage context later—judgment remains human edge"])
a(ep, g, name="Coding becomes calligraphy", quote="Coding is going to be like calligraphy… rare craft, commoditized output.", cat="Industry thesis", belief="Hand-written code becomes artisanal; default output is AI-generated.", op="Invest in product judgment and distribution; treat manual code as specialty not career default.", arch="Tech workforce in transition", h=["Review and architecture still need depth", "Regulated domains slow adoption"], pres=["Hiring freezes", "Tooling wars"], fail=["No one maintains generated systems", "Artisan bottleneck on hard problems"], con=["Everybody becomes engineer rhetoric vs hard eng still needed"], sig=["Elite eng admit AI writes all code"], emo=["Identity loss for coders", "Opportunity for non-traditional builders"], adapt=["Rapid engineer title → builder", "Pair vibe coders with staff eng"], ai=["Calligraphy analogy defines 5-year workforce split"])

# DR BECKY KENNEDY
ep, g = "A child psychologist's guide to working with difficult adults | Dr. Becky Kennedy", "Dr. Becky Kennedy"
a(ep, g, name="Repair as trust infrastructure", quote="Secure attachment has an adult who's willing to repair… sorry I yelled, I cut you off in the meeting.", cat="Relational leadership", belief="Trust compounds from recovery quality not flawless performance.", op="After misfire: timely specific accountability, impact acknowledgment, plan to change—without over-apologizing into power vacuum.", arch="High-trust product teams", h=["Repair sincere not weekly pattern", "Power gap allows honesty"], pres=["Public Slack blow-up", "CEO snaps in all-hands"], fail=["Performative apology", "Repair without behavior change"], con=["Repair vs sturdy boundaries—repair doesn't reverse decision"], sig=["Team disagrees again after incident"], emo=["Relief when leader owns harm", "Cynicism if scripted"], adapt=["Leader speaks first in retros", "Repair scripts"], ai=["Agents can't repair emotional debt—humans must"])
a(ep, g, name="Two hands: identity vs behavior", quote="This is a good person who is late… one hand identity, other hand behavior. We're on the same team.", cat="Performance management", belief="Collapsing behavior into identity triggers defensiveness and ends problem-solving.", op="Open with alliance and competence; explore systemic causes; treat as skill gap not moral verdict.", arch="Knowledge work teams", h=["Employee is good inside", "Issue is real not pretext"], pres=["PIP pathway", "Leader frustrated"], fail=["Gaslighting if performance truly bad", "Infinite empathy without consequences"], con=["Empathy plus enforcement—carry kid to car metaphor"], sig=["Employee explains root cause not character"], emo=["Shame drops", "Accountability rises"], adapt=["Ban lazy labels in feedback", "Two-hand framing training"], ai=["AI feedback drafts moralize—humans rewrite"])
a(ep, g, name="Most generous interpretation before intervention", quote="MGI… Did they not feel heard the first time?… private conversation, we're in a bad cycle.", cat="Conflict resolution", belief="Annoying behavior often encodes unmet need; diagnose need before policing symptom.", op="Generate 2–3 generous hypotheses; design intervention breaking vicious cycle.", arch="Cross-functional meeting dysfunction", h=["MGI not excuse for harm", "Time for private conversation"], pres=["Brilliant jerk before exec review"], fail=["MGI as never accountable", "Leader avoids conflict"], con=["MGI informs boundary not whether to hold it"], sig=["Shift from gossip to structured 1:1 experiments"], emo=["Target feels seen", "Peers stop triangulating"], adapt=["MGI in incident notes before HR"], ai=["Sentiment tools flag behavior; humans choose path"])
a(ep, g, name="Sturdy leadership contains without collapsing", quote="Turbulence doesn't scare me… I'll see you when we land… not opening cockpit to passengers.", cat="Executive presence", belief="Teams need leaders who validate emotion without outsourcing decisions to loudest anxiety.", op="Acknowledge feeling, affirm capability, state decision and rationale; reject dismissive and overwhelmed responses.", arch="Leaders during layoffs RTO pricing", h=["Decision defensible", "Leader holds heat without retaliating"], pres=["All-hands backlash", "Metric goal revolt"], fail=["Stone-walling empathy", "Performative certainty on bad call"], con=["Sturdy not cold—pairs with repair"], sig=["Noise rises then settles"], emo=["Relief plus residual anger"], adapt=["Pre-write sturdy scripts"], ai=["Leaders can't delegate political heat to ChatGPT"])
a(ep, g, name="Boundaries are what you will do", quote="Boundaries are what you tell someone you will do… Making a request, that's not a boundary.", cat="Boundary setting", belief="Power leaks when leaders confuse asking nicely with enforcing limits.", op="I will X if Y continues; accept emotional fallout as success; stop empty threats.", arch="Managers avoiding enforcement", h=["Leader has authority to execute", "Org backs enforcement"], pres=["Missed deadlines", "Toxic Slack"], fail=["Coercive overreach", "Punitive tone without validation"], con=["Connection before correction then enforce"], sig=["Fewer repeated violations"], emo=["Initial tantrum", "Long-term respect for limits"], adapt=["Document boundary scripts", "HR alignment"], ai=["Agent policy in code; humans enforce org boundaries"])
a(ep, g, name="Resilience over happiness optimization", quote="Optimizing for happiness in childhood is the quickest way to build anxiety… I believe you and I believe in you.", cat="Culture", belief="Short-term comfort optimization destroys long-term capacity.", op="On hard projects: validate difficulty, assert capability, don't remove struggle prematurely.", arch="High-performing ambitious teams", h=["Challenge growth-oriented not abusive", "Support exists"], pres=["Missed promotion", "Hard assignment"], fail=["Toxic what doesn't kill you", "Belief language without support"], con=["Resilience vs repair and connection"], sig=["Employees attempt hard tasks after validation"], emo=["Temporary discomfort", "Pride after completion"], adapt=["Two-foot feedback", "Celebrate struggle completion"], ai=["Don't let agents remove all friction—leaders need calibrated struggle"])

# MARC ANDREESSEN
ep, g = "Marc Andreessen: The real AI boom hasn't even started yet", "Marc Andreessen"
a(ep, g, name="Task loss precedes job loss", quote="Look at task loss… being good at two things is more than double the additive effect.", cat="Career strategy", belief="Jobs are task bundles; AI reassigns tasks before eliminating roles; multi-skill humans capture surplus.", op="Audit role by tasks; automate via AI; add complementary skills to become super-empowered specialist.", arch="Tech roles at AI-forward companies", h=["Org rewards breadth", "Depth needed to evaluate AI output"], pres=["Layoff fear", "Function territorialism"], fail=["Jack-of-all-trades mediocrity"], con=["Also says learn stack down to assembly for excellence"], sig=["Cross-functional prototypes", "Fewer handoffs"], emo=["Territorialism between PM/design/eng"], adapt=["Career ladders for task portfolio evolution"], ai=["Headcount stable while task graphs churn quarterly"])
a(ep, g, name="Agency as compounding lever", quote="AI should be the ultimate lever for a kid with agency… spend spare hours talking to AI.", cat="Talent", belief="In abundant intelligence, initiative not credentials determines compounding returns.", op="Hire and parent for live-player behavior; pair agency with stack literacy.", arch="Founders and accelerated learners", h=["Agency isn't chaos", "Safety rails exist"], pres=["Regulated industries block initiative"], fail=["Reckless automation", "Dunning-Kruger vibe coders"], con=["In order to lead learn to obey—agency within structure"], sig=["Self-directed projects unprompted"], emo=["Inspiration vs inequality anxiety"], adapt=["Bounded sandboxes", "Celebrate shipped side projects"], ai=["Talent pipeline age drops"])
a(ep, g, name="Atoms friction slows AI adoption", quote="Progress in bits… little progress in atoms… ChatGPT can't get a license to practice medicine.", cat="Macro strategy", belief="Transformation is real in bits-first domains; regulated physical economy lags decades.", op="Invest where verification is digital; expect healthcare/education/infra blocks; don't plan atoms disruption on software timelines.", arch="Venture investors and founders choosing sectors", h=["Regulatory capture persists"], pres=["AI doctor startups hit boards", "Hardware energy stalls"], fail=["Bits-only portfolio misses world", "Atoms plays die waiting"], con=["Demographic optimism may force atoms change eventually"], sig=["Founders pivot health to devtools"], emo=["Tech frustration vs institutional defense"], adapt=["Sector-specific regulatory strategy"], ai=["Two-speed world: software labor explodes, physical services reprice humans"])
a(ep, g, name="Demographics plus AI labor hedge", quote="If we didn't have AI we'd be in a panic… remaining human workers at a premium not a discount.", cat="Labor economics", belief="AI timing coincides with shrinking workforce—job-loss panic may overstate near-term displacement.", op="Model hiring for human scarcity in many markets; still train super-empowered individuals.", arch="Policy and workforce planners", h=["AI substitutes at scale", "Immigration stays low"], pres=["Rapid sector automation"], fail=["Complacency on reskilling", "Ignores distributional pain"], con=["Task loss churn within stable headcount"], sig=["Wage pressure in skilled roles concurrent with layoffs"], emo=["Hope narrative vs local fear"], adapt=["Scenario plan scarcity and surplus by segment"], ai=["Fewer entrants higher pay more bots per human"])
a(ep, g, name="Mexican standoff between functions", quote="PM, designer, engineer—everyone can do everyone else's job now… standoff until someone moves.", cat="Org dynamics", belief="AI collapses functional boundaries creating political equilibrium before new norms.", op="Explicitly negotiate new ownership rules; reward hybrids; avoid pretending old RACI still holds.", arch="Tech product orgs", h=["Leaders will reward outcomes not titles", "Quality gates remain"], pres=["AI coding for all roles", "Title protection"], fail=["Accountability vacuum", "Quality collapse"], con=["Everyone codes vs hard eng still required"], sig=["PRs from non-traditional roles", "Territorial escalation"], emo=["Status anxiety", "Arms race of tooling"], adapt=["Builder title and promotion criteria"], ai=["Political capital follows merge rights not function"])

# JASON COHEN
ep, g = "5 questions to ask when your product stops growing | Jason Cohen (2x unicorn founder)", "Jason Cohen"
a(ep, g, name="Churn ceiling arithmetic", quote="New customers per month divided by cancellation rate… you will never have more than X customers.", cat="Growth diagnostics", belief="Logo churn creates hard asymptote; marketing cannot outrun percentage leakage.", op="First stalled-growth diagnostic: max customers = acquisitions / monthly logo churn %; treat 3%+ SMB monthly churn as emergency.", arch="SaaS with PLG or sales-assist", h=["Churn rate stable by segment", "Acquisition metric honest"], pres=["Plateau at 2x ARR", "Investors push paid spend"], fail=["Chasing channels while bucket leaks"], con=["Framework continues to pricing and channels—order matters"], sig=["Flat customer count despite rising spend"], emo=["Growth vs product blame"], adapt=["Churn war room before budget increases"], ai=["Easier build masks fit problems—more signups same ceiling faster"])
a(ep, g, name="What made you cancel beats why", quote="What made you cancel gets 20% responses vs 10%… too expensive is never ever the reason.", cat="Churn research", belief="Proximate excuses hide product failures; phrasing determines signal quality.", op="Causal framing in exit surveys; randomize multiple-choice order; drill past too expensive; interview at-risk before cancel.", arch="B2B SaaS self-serve cancel", h=["Volume for patterns", "Team acts on ugly truths"], pres=["Spike in project ended"], fail=["Overfitting noisy text", "LLM averages away actionable detail"], con=["Use AI for themes human for specifics"], sig=["Roadmap shifts to onboarding after drills"], emo=["Founder grief on gauntlet narrative"], adapt=["Root-er cause sessions", "Fix onboarding if unsure"], ai=["Agents can interview churners 24/7—still need causal questions"])
a(ep, g, name="Pricing selects the market", quote="Raise prices and signups don't change… you're not near the price yet.", cat="Pricing", belief="Price is positioning signal; microeconomic demand curves mislead in B2B.", op="Test large increases especially upmarket; reframe value from cost-saving to growth outcomes.", arch="Bootstrapped and VC SaaS underpricing", h=["Buyer segment can pay", "Product supports enterprise if selected"], pres=["Founder fear of fewer signups"], fail=["Pricing out wrong segment", "No capacity for enterprise promises"], con=["Fix churn before raising price on broken product"], sig=["Flat signups jumping ACV"], emo=["Sales resists", "Product strained by enterprise reqs"], adapt=["Stepwise 2x tests with positioning rewrite"], ai=["Commoditized software pushes positioning over price"])
a(ep, g, name="NRR and expansion as growth lever", quote="If NRR is below 100% you're shrinking even with new logos… expansion revenue is often the real growth engine.", cat="Retention economics", belief="Net revenue retention reveals whether existing base compounds or erodes.", op="When growth stalls after churn check: analyze expansion paths, packaging, and account growth—not only acquisition.", arch="B2B SaaS with land-and-expand potential", h=["Product delivers expanding value over time", "Sales can upsell without breaking trust"], pres=["Land-and-expand ICP", "Usage-based potential"], fail=["Forced expansion damaging trust", "Misread NRR conflated with pricing only"], con=["PLG vs enterprise expansion paths differ"], sig=["NRR under 100% with positive logo growth"], emo=["Sales celebrates new logos while revenue flat"], adapt=["Expansion playbook before new channel spend"], ai=["AI usage-based pricing can inflate NRR if value scales with consumption"])
a(ep, g, name="Channel saturation diagnostic", quote="When a marketing channel stops working it often means you've exhausted the audience not that marketing is broken.", cat="Go-to-market", belief="Stalled growth may be channel-product fit exhaustion not product death.", op="After retention and pricing: test whether CAC inflation reflects ICP saturation; consider new ICP or channel before product pivot.", arch="SaaS with single dominant acquisition channel", h=["ICP definable", "Channel metrics trustworthy"], pres=["Rising CAC", "Flat conversion on spend increase"], fail=["Abandoning product when channel saturated", "Infinite channel spend"], con=["Product problem vs channel problem sequencing"], sig=["CAC up conversion flat", "Same channel worked for years then didn't"], emo=["Panic pivot to new product", "Marketing blamed unfairly"], adapt=["ICP expansion or second channel before rebuild"], ai=["AEO and AI discovery as new channel layer—not replacement for fit"])
a(ep, g, name="ICP wrong market diagnostic", quote="Sometimes the market you picked is the problem… gauntlet of whether anyone wants this.", cat="Strategy", belief="No amount of optimization fixes fundamental market or ICP mismatch.", op="Fifth question when other four exhausted: is this the right market segment; willingness to pivot ICP or product.", arch="Early and mid-stage B2B", h=["Honesty to kill sacred cows", "Runway for pivot"], pres=["All levers tried", "Founder denial"], fail=["Eternal grind on wrong ICP", "Pivot theater without customer pull"], con=["Pivot vs persist founder psychology"], sig=["Low win rate despite good execution", "Churn reasons cluster on wrong job"], emo=["Founder identity tied to original vision"], adapt=["Structured ICP experiments", "Paid discovery before rebuild"], ai=["Faster build makes wrong-market exploration cheaper but also more seductive"])

# ZEVI ARNOVITZ
ep, g = "The non-technical PM's guide to building with Cursor | Zevi Arnovitz (Meta)", "Zevi Arnovitz"
a(ep, g, name="Phased slash-command workflow", quote="/create issue… /exploration phase… /create plan… execute… peer review… never let coding agent start without plan on payments.", cat="Builder workflow", belief="Eager coders human or AI destroy compounding systems without planning gate.", op="Linear issue → exploration questions → plan.md → execute → multi-model review → update docs.", arch="Non-technical PM at Meta plus solo monetized side project", h=["MCP integrations reliable", "Eng tolerates PM-owned repos"], pres=["Live demo pressure", "Payment migration"], fail=["Ceremony fatigue", "Skipping review when fast"], con=["Meta tickets are exploration starters not build-ready"], sig=["plan.md on every complex issue"], emo=["Eng skepticism until incident-free ships"], adapt=["Share commands company-wide", "Staff eng on auth/payments only"], ai=["PMs become workflow engineers; prompts as code"])
a(ep, g, name="Multi-model peer review for non-coders", quote="/review… Codex and Cursor each review… can't catch mistakes by reading code.", cat="Quality assurance", belief="When author can't read diffs, adversarial models plus structured review are inspection layer.", op="Multiple models review before merge; /learning opportunity for mental models not syntax.", arch="Technical-adjacent PM shipping production", h=["Models disagree usefully", "Review prompts catch security"], pres=["Monetized app without eng background"], fail=["Correlated errors across families", "False confidence"], con=["Exposure therapy to code but avoids reading diffs"], sig=["Review clustered before merge"], emo=["Eng nervous until track record"], adapt=["Human stamp for payments/auth"], ai=["QA becomes review-prompt curator"])
a(ep, g, name="Graduated tool onboarding ladder", quote="Start GPT project → Lovable → Cursor dark mode… meet yourself where you are.", cat="Adoption", belief="Tool complexity must match current skill or abandonment happens at step change.", op="Progressive tool ladder; don't jump to Cursor day one without product thinking foundation.", arch="Non-technical PM learning to ship", h=["Time to learn each step", "Problem worth solving exists"], pres=["Pressure to ship like influencers"], fail=["Tool hopping without finishing", "Cursor overwhelm"], con=["Eventually all-in on Cursor—ladder still valid"], sig=["Side project before work adoption"], emo=["Imposter syndrome", "Excitement at first Lovable ship"], adapt=["Lovable for activation Cursor for production"], ai=["Onboarding paths multiply—ladder more important"])
a(ep, g, name="Exploration phase before codegen mandate", quote="Tickets are not ready for build—they're ready for exploration. Clarifying questions first.", cat="Product process", belief="Ambiguity cheap at start expensive after agent wrote 500 lines.", op="Mandatory exploration slash command generates questions before plan or code on complex domains.", arch="PM-led development on high-risk features", h=["Team accepts delay for clarity", "Exploration actually updates plan"], pres=["Stakeholder wants demo Friday", "Payments scope"], fail=["Exploration theater without plan update", "Skip on small bugs create precedent"], con=["Speed culture vs exploration gate"], sig=["Long exploration outputs in tickets", "Fewer revert commits"], emo=["PM guilt slowing down", "Eng appreciation after"], adapt=["Risk-tiered: skip only truly trivial"], ai=["Agents make skipping exploration more dangerous not less"])

# SAM LESSIN
ep, g = "How to show up in any room with a low heart rate | Sam Lessin", "Sam Lessin"
a(ep, g, name="Abundance mindset in high-stakes rooms", quote="Show up with self-confidence and calm of abundance. This is part of the story, not the entire story.", cat="Founder presence", belief="Scarcity behavior repels deals; calibrated calm signals trustworthiness.", op="Before high-stakes rooms: breathe, ping-pong dialogue not monologue, exit before exhausting room.", arch="Young technical founders entering VC networks", h=["Product good enough to not need desperation"], pres=["Kleiner parties", "Famous-person encounters"], fail=["Performative chill while absent", "Charm without follow-through"], con=["Admits personal hypocrisy on punctuality"], sig=["Follow-up meetings scheduled", "Introductions unprompted"], emo=["Peers relax", "Less post-meeting cringe"], adapt=["YC etiquette framing", "Flash tags for urgency"], ai=["When code commoditizes trust and distribution re-price"])
a(ep, g, name="Ping-pong not monologue", quote="Hit the ball back… if you hit 10 balls at them in a row, that's not the vibe.", cat="Communication", belief="High-status rooms reward reciprocal dialogue not pitch dumps.", op="Structure conversations as exchange; prepare questions; leave wanting more.", arch="Founders in investor and partnership meetings", h=["Counterparty wants to talk too", "You have real substance when it's your turn"], pres=["Short meeting slots", "Panel formats"], fail=["Overselling", "No listening—no second meeting"], con=["Still need to convey vision in limited time"], sig=["Interruptions welcomed as engagement", "They ask follow-ups"], emo=["Anxiety drives monologue", "Relief when mirrored"], adapt=["Prep three questions per meeting", "Practice out loud"], ai=["AI prep decks don't replace conversational give-and-take"])
a(ep, g, name="Signaling effort matters", quote="What matters is signaling of effort as much as the actual thing… neurodivergent grace, but make an effort.", cat="Trust", belief="Observers forgive imperfection when visible attempt to respect norms exists.", op="Dress to room plus one; hygiene neutral; appropriate video background; offer to pay within reason.", arch="Remote-first startups meeting enterprise", h=["Norms legible", "Effort reads sincere"], pres=["First enterprise dinner", "Podcast appearance"], fail=["Over-signaling Rolex founder", "Authenticity gap"], con=["Teaches rules while wearing T-shirt"], sig=["Fewer odd vibe debriefs"], emo=["Class and neurodivergence tension"], adapt=["Separate substance vs polish feedback"], ai=["Deepfakes raise bar for proving human effort in trust deals"])
a(ep, g, name="Vibe code prototype then engineer scale", quote="Vibe coding good for first version… doesn't really scale… friends up level what I ran out of time for.", cat="Build strategy", belief="AI solo build proves concept; production hardening needs engineers.", op="Founder/exec builds v1 with Cursor stack; hands to eng for scale security performance.", arch="Operator with eng friends", h=["Engineers available", "Scope fits vibe window"], pres=["Demo success pressure", "Security requirements"], fail=["Prod on vibe-only stack", "Never handing off"], con=["Evangelizes vibe while requiring eng for scale"], sig=["Personal tools shipped", "Eng refactor after"], emo=["Pride in solo build", "Relief when eng takes over"], adapt=["Explicit handoff criteria", "Security review gate"], ai=["Default pattern: vibe POC → eng production"])
a(ep, g, name="Emoji and jokes as familiarity risk", quote="Emojis almost feel like jokes… tell them at your own risk… making fun of yourself is always fun.", cat="Communication norms", belief="Familiarity signals in business context can backfire without established trust.", op="Match vocabulary of counterparty; avoid emoji until mirrored; self-deprecating humor safer than mocking others.", arch="High-stakes business communication", h=["Cultural context varies", "Relationship has baseline trust"], pres=["First email to exec", "Cross-cultural teams"], fail=["Offensive humor", "Emoji misread as unprofessional"], con=["Casual SV norms vs enterprise formality"], sig=["Mirror language gradually"], emo=["Fear of being boring", "Relief when matched"], adapt=["Default formal until mirrored"], ai=["AI drafts may over-casualize—human edits tone"])

# ALEXANDER EMBIRICOS
ep, g = "The power user's guide to Codex | Alexander Embiricos", "Codex"
a(ep, g, name="Local-first pairing before cloud delegation", quote="Codex Cloud was hard to adopt… IDE extension or CLI… strong feedback loop… then delegate.", cat="Adoption", belief="Adoption mirrors hiring: side-by-side before async delegation.", op="Onboard via local sandboxed CLI/IDE; graduate to parallel cloud agents after correction loop learned.", arch="OpenAI Codex team vs market", h=["Sandbox security holds", "Local friction minimized"], pres=["Competitor cloud-agent narrative"], fail=["Never graduating to delegation", "Cloud starved"], con=["Internal massive parallel usage after curve"], sig=["IDE funnel converts then cloud grows"], emo=["Power users feel patronized", "Novices relieved"], adapt=["Coach delegation during local wins"], ai=["Onboarding UX is moat—models commoditize"])
a(ep, g, name="Review UX as product moat", quote="Reviewing AI code is often less fun… show the image first, not the diff.", cat="Product strategy", belief="Bottleneck moved from authoring to verification; winner optimizes confidence per minute.", op="Invest in automated review visual previews before raw diffs; fun as design metric.", arch="Coding agent vendors post-2025", h=["Visual preview suffices often", "Security still caught on risk-tier"], pres=["100 PRs per engineer per week"], fail=["Rubber-stamping pretty UI", "Missed logic bugs"], con=["Codex reviews own code—circular trust"], sig=["Time-to-merge down", "Reviewer satisfaction up"], emo=["Engineers mourn writing flow"], adapt=["Mandatory diff for auth/payments"], ai=["PM owns verification experience"])
a(ep, g, name="Integrated model-harness-API stack", quote="Compaction uses all three layers… model, API, harness… building all three in parallel.", cat="Technical strategy", belief="Agent quality is system property; split vendors slow long-horizon iteration.", op="Co-develop model with first-party harness and sandbox; ship cross-layer features like compaction together.", arch="Vertically integrated AI lab", h=["Customers accept some lock-in", "Research-product alignment"], pres=["Benchmark wars", "Customers want model inside Cursor only"], fail=["Fragile monolith", "Slow cross-platform adoption"], con=["API sold to partners while building app"], sig=["24h agent tasks", "Compaction shipped cross-layer"], emo=["Platform vs app tension"], adapt=["Versioned harness spec"], ai=["Competition is vertical stacks not single models"])
a(ep, g, name="Compress talent stack via prototyping", quote="Boundaries between roles less needed… designers vibe side prototype… PM prototypes faster than specs.", cat="Cross-functional execution", belief="When individuals ship, organizational interfaces shrink.", op="Designers maintain parallel vibe app; PMs throwaway analyses; engineers own hard paths.", arch="OpenAI product/design/eng on Codex Sora", h=["Prototype doesn't contaminate prod", "Leaders reward breadth"], pres=["28-day App Store push"], fail=["Unreviewed prototype in prod", "Accountability diffusion"], con=["Still need eng for hard landing"], sig=["Demos not decks in meetings"], emo=["Eng fear ownership blur"], adapt=["Separate prototype repos", "Promotion for hybrids"], ai=["Org charts flatten; merge rights equal power"])
a(ep, g, name="Compaction for long-horizon agents", quote="Compaction… lets agents run for a very long time without running out of context.", cat="Agent architecture", belief="Long tasks require explicit memory management across model API and UI.", op="Implement compaction in harness not only prompts; design tasks assuming summarization and state externalization.", arch="Long-running agent products", h=["Compaction doesn't lose critical state", "Users trust long runs"], pres=["Overnight agent jobs", "Multi-hour refactors"], fail=["Silent state loss after compaction", "User confusion on what agent remembers"], con=["Context engineering vs compaction abstraction"], sig=["Public 24h run stories", "Fewer manual restarts"], emo=["Awe and fear of unattended agents"], adapt=["Checkpointing plus compaction", "Human review at phase boundaries"], ai=["Long-horizon agents become default for complex work"])

if __name__ == "__main__":
    out = "operational-intelligence-batch2.json"
    with open(out, "w") as f:
        json.dump(P, f, indent=2)
    from collections import Counter
    c = Counter(x["source_guest"] for x in P)
    print(f"Wrote {len(P)} objects to {out}")
    for g, n in sorted(c.items(), key=lambda x: -x[1]):
        print(f"  {n:2d}  {g}")
